# -*- coding: utf-8 -*-
"""Urology flashcard content — source: Urology Teaching Series slide decks."""

# ============================================================
# GROUP 01 — Uro-Oncology
# ============================================================
uro_onco = [
 {"cat":"Prostate","q":"What are the 3 well-established risk factors for prostate cancer?",
  "a": "<ul><li><b>Increasing age</b> — single most important demographic factor</li><li><b>Ethnic origin</b> — e.g., Japanese men have a low incidence</li><li><b>Heredity</b> — 1 first-line relative doubles risk; 2+ relatives → 5–11-fold increase</li></ul>PCa is the most common solid neoplasm in Europe and 2nd most common cause of cancer death in men."},
 {"cat":"Prostate","q":"What are the PSA and its derivatives in prostate cancer?",
  "a": "PSA is a glycoprotein (serine protease) produced by benign and malignant prostate tissue; normal ≤2.5–4 ng/mL by age. Derivatives: <b>free/total PSA ratio</b>; <b>PSA density</b> (PSA ÷ prostate volume; &gt;0.15 = high risk); PSA velocity."},
 {"cat":"Prostate","q":"How is prostate cancer diagnosed and staged?",
  "a": "Diagnosis: symptoms/signs (DRE — induration), PSA, <b>TRUS-guided biopsy</b> confirms histology, diagnostic TURP. Local staging (T): <b>MR imaging</b> + DCE-MRI in equivocal cases. Metastasis staging: <b>bone scan</b> for skeletal mets; PET/CT or whole-body MRI in equivocal cases; PLND for nodal spread."},
 {"cat":"Prostate","q":"Explain the Gleason score.",
  "a": "Grading of adenocarcinoma of the prostate (which is &gt;95% of prostate cancers) by low-power glandular architecture: patterns 1–5 (1 = well-formed closely packed glands → 5 = no glandular differentiation, sheets). <b>Score = sum of the two most common patterns; ranges 2–10</b> (2 least aggressive, 10 most aggressive)."},
 {"cat":"Prostate","q":"Describe the androgen axis and the two routes of androgen deprivation.",
  "a": "Hypothalamus → LHRH → pituitary LH/FSH → Leydig cells → testosterone → <b>5-α-reductase converts T to DHT (≈10× more powerful)</b>. Depriving prostate cells of androgen → apoptosis. <b>Routes:</b> (1) suppress testicular androgen secretion — surgical (bilateral orchiectomy) or medical castration (LHRH agonists/antagonists); (2) inhibit action of circulating androgens — <b>anti-androgens</b> (compete with T/DHT at receptor). Complete androgen blockade = castration + anti-androgen."},
 {"cat":"Prostate","q":"Summarize treatment of prostate cancer by stage (T1/T2).",
  "a": "<b>T1:</b> watchful waiting / active surveillance (standard for Gleason ≤6, ~10-year life expectancy), radical prostatectomy, or radiotherapy; hormonal therapy not an option. <b>T2:</b> <b>radical prostatectomy</b> (standard for 10-year survival), radiotherapy, brachytherapy (low-risk, small prostate); hormonal therapy only for palliation; combination for high-risk."},
 {"cat":"Bladder","q":"List the inducing agents (carcinogens) of bladder cancer.",
  "a": "Viruses; chemical carcinogens — <b>aniline dyes</b>; cigarette smoking (nitrosamines, 2-naphthylamine, 4-aminobiphenyl); coffee; analgesics (phenacetin); artificial sweeteners; bacterial/parasitic/fungal infections; bladder calculi; genotoxic chemotherapeutic agents. Bladder cancer is &gt;2.5× more common in men; 4th most common cancer in men."},
 {"cat":"Bladder","q":"What is the geographic variation of squamous cell carcinoma of the bladder?",
  "a": "SCC: 1% of bladder cancers in England, 3–7% in the USA, <b>40–75% in Egypt</b> — ~80% of Egyptian SCCs associated with chronic <b>Schistosoma haematobium</b> infection. Patients are 10–20 years younger than TCC patients; bilharzial cancers are exophytic/nodular, well-differentiated, with relatively low metastasis."},
 {"cat":"Bladder","q":"Describe the patterns of spread of bladder cancer.",
  "a": "<b>Direct extension:</b> en bloc (~60%), tentacle-like (~25%), lateral spread under normal mucosa (~10%). <b>Implantation</b> in wounds/denuded urothelium. <b>Lymphatic</b> (pelvic nodes): obturator 74%, external iliac 65%, paravesical 16%, presacral ~25%. <b>Vascular:</b> liver, lung, bone."},
 {"cat":"Bladder","q":"What is the most common presentation of bladder cancer?",
  "a": "<b>Painless hematuria — ~85%</b>. Second: bladder irritability — frequency, urgency, dysuria (usually with diffuse CIS or invasive cancer). Advanced: flank pain (ureteral obstruction), lower limb edema, pelvic mass, weight loss."},
 {"cat":"Bladder","q":"Give the TNM staging of bladder cancer (T).",
  "a": "<ul><li><b>Ta:</b> papillary, epithelium-confined</li><li><b>Tis:</b> flat carcinoma in situ</li><li><b>T1:</b> lamina propria invasion</li><li><b>T2a/b:</b> muscle-invasive (superficial/deep)</li><li><b>T3a/b:</b> perivesical fat (micro/macroscopic)</li><li><b>T4a:</b> pelvic viscera (prostate, rectum, uterus, vagina)</li><li><b>T4b:</b> pelvic sidewall/abdominal wall</li></ul>N1 ≤2 cm single node; N2 2–5 cm; N3 &gt;5 cm."},
 {"cat":"Bladder","q":"How is non-muscle-invasive bladder cancer (NMIBC) treated?",
  "a": "<b>TURBT</b> (resect whole lesion + sample underlying muscle); <b>intravesical therapy</b> — chemotherapy (mitomycin C) or <b>BCG</b> — reduces recurrence; photodynamic diagnosis with photosensitizers (hexa-aminolaevulinic acid) enhances tumor visibility; <b>radical cystectomy</b> for high-grade NMIBC failing TURBT + intravesical therapy."},
 {"cat":"Upper tract","q":"What are the risk factors for upper urinary tract urothelial tumors?",
  "a": "Male gender and increasing age; <b>smoking — the most important risk factor (2–3×)</b> (chemical carcinogens: aniline, benzidine, aromatic amines, azo dyes); cyclophosphamide; heavy caffeine; chronic inflammation/infection; occupational exposure. TCC frequency: bladder &gt; renal pelvis &gt; ureter (125 : 2.5 : 1)."},
 {"cat":"Upper tract","q":"What is the gold-standard treatment of upper tract urothelial tumors?",
  "a": "<b>Radical nephroureterectomy + bladder cuff excision</b> — remove kidney + entire ureter including orifice (multifocality + high ipsilateral recurrence after partial resection). Endoscopic resection/fulguration for: solitary kidney, bilateral disease, renal dysfunction, intercurrent illness, selected small low-grade lesions."},
 {"cat":"Renal","q":"List the benign renal tumors and the Bosniak classification.",
  "a": "Commonest benign: renal cysts, <b>oncocytoma</b>, <b>angiomyolipoma</b>, renal adenomas. <b>Bosniak I:</b> thin wall, water density, no septa/calcification/enhancement. II: thin septa and/or fine calcification. (III/IV: more complex — suspicious/malignant.)"},
 {"cat":"Renal","q":"Give the overview and risk factors of renal cell carcinoma.",
  "a": "RCC = <b>85% of primary malignant renal tumors</b>; 5th–6th decade; M:F 3:2; grossly common in the upper pole; microscopic: clear cell, papillary, chromophobe, collecting duct. Risk factors: smoking, obesity, genetic (chromosomes 3 &amp; 7), <b>Von-Hippel-Lindau disease</b>, tuberous sclerosis, cystic disease on dialysis."},
 {"cat":"Renal","q":"Summarize the 2017 TNM staging of RCC.",
  "a": "<b>T1:</b> ≤7 cm, limited to kidney. <b>T2:</b> &gt;7 cm (≤10), limited to kidney. <b>T3:</b> into major veins or perinephric tissues, within Gerota fascia — T3a: renal vein/segmental branches, pelvicalyceal system, perirenal/sinus fat; T3b: IVC below diaphragm; T3c: IVC above diaphragm or caval wall invasion. <b>T4:</b> beyond Gerota fascia (incl. ipsilateral adrenal)."},
 {"cat":"Renal","q":"What is the clinical picture and treatment of RCC?",
  "a": "Classic triad: gross hematuria, loin pain, palpable mass (rare today — most are incidental). Also metastasis, secondary varicocele, paraneoplastic (Stauffer syndrome, anemia, erythrocytosis, amyloidosis, hypercalcemia). Treatment: localized → <b>radical nephrectomy</b>; metastatic → radiotherapy, chemotherapy, immunotherapy, hormonal therapy, surgery."},
 {"cat":"Testis","q":"Give the key facts of testicular tumors (epidemiology, aetiology, presentation).",
  "a": "Most common GU malignancy in males <b>15–35 years</b>; cure rate ~90%; more common on the right; more common in Caucasians. Aetiology: <b>cryptorchidism — commonest risk factor</b> (orchiopexy does not prevent cancer), orchitis/trauma, HIV, family history, CIS, atrophy. Presentation: painless scrotal lump; acute pain in 10% (hemorrhage); gynecomastia in 5% (functional metastasis)."},
 {"cat":"Testis","q":"Classify germ cell tumors of the testis.",
  "a": "<b>Seminoma (40%):</b> 70% confined to testis; radio- and chemo-sensitive; classic (80%), spermatocytic (best prognosis, &gt;50 y), anaplastic (worse). <b>Non-seminomatous (main 4):</b> yolk sac (most common in infancy; <b>AFP ↑ in 90%</b>), embryonal carcinoma (smallest, highly malignant), teratoma (bone/cartilage/intestinal tissue), <b>choriocarcinoma (worst prognosis; HCG ↑ in all)</b>. Non-germ cell: Sertoli/Leydig cell tumors."},
 {"cat":"Testis","q":"How are testicular tumors diagnosed and treated?",
  "a": "Diagnosis: scrotal duplex US, CT chest/abdomen/pelvis, PET. Treatment: <b>ipsilateral radical orchiectomy first</b> (also diagnostic), then radiotherapy, chemotherapy, retroperitoneal lymph node dissection as staged. pT1: limited to testis/epididymis, no vascular invasion; pT2: with vascular invasion or tunica vaginalis involvement."},
]

# ============================================================
# GROUP 02 — Stones & Infections
# ============================================================
stones = [
 {"cat":"Stones","q":"Give the incidence and classification of urinary stones.",
  "a": "Affect <b>10–20%</b> of the population; males 1–2× more; <b>3rd most common urinary tract disease</b>; recurrence 50–60% within 10 years. By composition: <b>calcium 70–80%</b>, infected (struvite) 10–20%, uric acid 5–10%, cystine 1–2%, miscellaneous &lt;5%. By X-ray: radiopaque vs radiolucent (uric acid)."},
 {"cat":"Stones","q":"Describe the three levels of saturation and the theories of stone formation.",
  "a": "<b>Undersaturated:</b> stones dissolve; no aggregation. <b>Saturated (metastable):</b> nucleation/growth possible but inhibitors can prevent it. <b>Supersaturated:</b> inhibitors ineffective, nucleation occurs. Theories: nucleation (homogeneous or heterogeneous/epitaxy), matrix initiation (urine proteins as framework), absence of inhibitors (↓mucoprotein)."},
 {"cat":"Stones","q":"List the causes of calcium, uric acid and cystine stones.",
  "a": "<b>Calcium stones:</b> hypercalcemia (hyperparathyroidism, vitamin D excess, bone mets), <b>hypercalciuria (most common cause)</b>, hyperoxaluria, hypocitraturia, hyperuricosuria. <b>Uric acid stones:</b> hyperuricemia (gout, neoplastic disease). <b>Cystine stones:</b> autosomal recessive defect of dibasic amino acid (cysteine, lysine, arginine) reabsorption in renal tubules."},
 {"cat":"Stones","q":"What are the four major complications of urinary stones?",
  "a": "1. <b>Obstruction</b> (back-pressure → hydronephrosis → nephropathy), 2. <b>Infection</b> (stone + infection = <b>pyonephrosis — emergency</b>), 3. <b>Deterioration of renal function</b>, 4. <b>Chronic irritation</b> → metaplasia/malignant transformation."},
 {"cat":"Stones","q":"Describe the pain distribution of ureteric stones.",
  "a": "<b>Upper third:</b> flank pain with referred pain to the <b>testicle</b>. <b>Lower third:</b> flank pain, lower-quadrant pain, radiating to the <b>scrotum or vulva</b>."},
 {"cat":"Stones","q":"What does a plain KUB show and what is the differential of a radio-opaque shadow?",
  "a": "Diagnoses radio-opaque and soft-tissue shadows. DDx: urinary stones, gall bladder stones, phleboliths, appendicolith, GIT foreign bodies, nephrocalcinosis, calcified renal cyst/tumor, calcified mesenteric nodes, chip fracture of transverse process/rib."},
 {"cat":"Stones","q":"What are the indications and contraindications of ESWL?",
  "a": "Principle: acoustic shock waves focused on the stone (X-ray/US) fragment it into particles. Indication: stones <b>≤2 cm</b>. Contraindications: urological (associated pathology needing intervention, acute UTI, distal obstruction, larger stones, renal insufficiency, single renal unit unless stented) and non-urological (pregnancy, bleeding disorders…)."},
 {"cat":"Stones","q":"What are the indications for PCNL?",
  "a": "Stones <b>&gt;2 cm</b>; staghorn stones; ESWL failure; associated pathology manipulable percutaneously (e.g., PUJO). Procedure: puncture calyx → guide wire → dilate tract (Amplatz sheath) → nephroscope → stone extraction or lithotripsy → nephrostomy 1–2 days."},
 {"cat":"Stones","q":"How are ureteric stones managed by site?",
  "a": "<b>Upper third:</b> 1) ESWL, 2) ureteroscopy + laser, 3) open surgery. <b>Middle third:</b> 1) ureteroscopy + laser, 2) ESWL, 3) open. <b>Lower third:</b> 1) ureteroscopy, 2) ESWL, 3) open."},
 {"cat":"Stones","q":"When is open surgery (cystolithotomy) indicated for bladder stones?",
  "a": "Large stones not manipulable endoscopically; multiple or very hard stones; diverticular stones; pediatric bladder calculi (without laser); associated pathology needing open surgery. Otherwise: endoscopic litholapaxy or lithotripsy."},
 {"cat":"Stones","q":"What is the metabolic work-up and prevention of stone recurrence?",
  "a": "Serum Ca/P (exclude hyperparathyroidism), uric acid (gout); 24-h urine calcium (300 mg), uric acid (800 mg), oxalate (40 mg), citrate (300–900 mg) for a 60-kg adult. General: high fluid intake, restrict dietary salt/protein, avoid obesity. Calcium oxalate: low-oxalate diet, HCTZ 50 mg bid, citrates 5 g bid. Uric acid: avoid purines, keep urine alkaline (NaHCO₃), rule out myeloproliferative disease."},
 {"cat":"UTI","q":"What is significant bacteriuria and the gold standard of UTI diagnosis?",
  "a": "Gold standard: <b>detection of the pathogen (midstream urine culture) in the presence of clinical symptoms</b>. Thresholds: uncomplicated cystitis ≥10³ cfu/mL; pyelonephritis ≥10⁴ cfu/mL; classic significant bacteriuria ≥10⁵ cfu/mL (also in pyelonephritis of pregnancy, Kass); complicated UTI (men) ≥10⁴; any count on suprapubic puncture."},
 {"cat":"UTI","q":"What is the pathogenesis of UTI and catheter-related risk?",
  "a": "<b>E. coli causes 85% of ambulatory and 50% of nosocomial UTIs</b>; then Proteus, Klebsiella, Enterococcus. Route: <b>retrograde ascent from fecal flora</b> via urethra to bladder/kidney. Single catheter insertion → UTI in 1–2%; indwelling catheters with open drainage → bacteriuria in nearly 100% within 3–4 days. Hematogenous spread only for a few microbes (S. aureus, Candida)."},
 {"cat":"UTI","q":"Define uncomplicated vs complicated UTI.",
  "a": "<b>Uncomplicated:</b> acute cystitis/pyelonephritis in otherwise healthy individuals (E. coli 70–95%, S. saprophyticus 5–10%). <b>Complicated:</b> structural/functional abnormalities, indwelling catheters/stents, obstructive uropathy, renal insufficiency, transplant, diabetes, immunodeficiency, VUR, urinary diversions (ileal loop)."},
 {"cat":"UTI","q":"How is acute uncomplicated cystitis treated?",
  "a": "<b>Cotrimoxazole 160/800 mg bid × 3 days</b> (classic first-line) or trimethoprim 200 mg × 5 days; alternative ciprofloxacin 250 mg bid when resistance/intolerance. Diagnosis: ≥10³ cfu/mL; culture if suspected pyelonephritis or symptoms don't resolve/recur within 2–4 weeks."},
 {"cat":"UTI","q":"How is acute uncomplicated pyelonephritis treated?",
  "a": "Diagnosis ≥10⁴ cfu/mL; US to exclude obstruction/stones; CT or DMSA if persistent. Mild: <b>oral fluoroquinolone × 7 days</b>. Severe: admission, <b>parenteral fluoroquinolone or 3rd-generation cephalosporin</b>, then oral continuation 1–2 weeks."},
 {"cat":"UTI","q":"How are UTIs managed in pregnancy?",
  "a": "Asymptomatic bacteriuria in 4–7% of pregnant women; <b>20–40% progress to pyelonephritis</b> — treat asymptomatic bacteriuria. Prophylaxis: low-dose cephalexin (125–250 mg) or nitrofurantoin (50 mg) nightly. Acute pyelonephritis: 2nd/3rd-gen cephalosporins or aminoglycoside. <b>Quinolones, tetracyclines and TMP are contraindicated in the 1st trimester.</b>"},
 {"cat":"UTI","q":"What are the three groups of recurrent UTI?",
  "a": "<b>1. Unresolved infection</b> — subtherapeutic antibiotic, non-compliance, malabsorption, resistant pathogens. <b>2. Bacterial persistence</b> — a nidus in the urinary tract (may need surgical correction). <b>3. Reinfection</b> — new infection from periurethral/perineal/rectal flora. In post-menopausal women: <b>intravaginal oestriol</b> significantly reduces recurrence."},
 {"cat":"UTI","q":"Describe urosepsis and its treatment.",
  "a": "SIRS (fever/hypothermia, leucocytosis/leucopenia, tachycardia, tachypnoea) is the first event → sepsis/septic shock → multi-organ failure. Prognosis better than sepsis from other sites but mortality up to <b>20–40%</b>. Treatment: resuscitation + source control (relieve obstruction, drainage) + antibiotics."},
 {"cat":"UTI","q":"How are gonorrhoea and chlamydial urethritis treated?",
  "a": "<b>Gonorrhoea:</b> ceftriaxone 125 mg IM single dose (or cefixime 400 mg, ciprofloxacin 500 mg, ofloxacin 400 mg, levofloxacin 250 mg orally). <b>Chlamydia:</b> azithromycin 1 g single dose or doxycycline 100 mg bid × 7 days. <b>Always dual therapy for both</b> — co-infection is common."},
 {"cat":"UTI","q":"Give the NIDDK/NIH classification of prostatitis and treatment.",
  "a": "<b>I:</b> acute bacterial prostatitis (admission + parenteral antibiotics, then oral 2–4 weeks). <b>II:</b> chronic bacterial prostatitis. <b>III:</b> chronic abacterial prostatitis/CPPS (A: inflammatory — white cells; B: non-inflammatory). <b>IV:</b> asymptomatic inflammatory prostatitis. Chronic: <b>ciprofloxacin/levofloxacin 4–6 weeks</b> (best pharmacokinetics)."},
]

# ============================================================
# GROUP 03 — Functional Urology & Andrology
# ============================================================
functional = [
 {"cat":"Incontinence","q":"Define the types of urinary incontinence.",
  "a": "<ul><li><b>Stress:</b> involuntary loss on exertion, sneezing, coughing</li><li><b>Urge:</b> loss preceded by urgency (involuntary detrusor contraction)</li><li><b>Mixed:</b> stress + urge</li><li><b>Overflow:</b> leakage with urinary retention/bladder over-distension</li><li><b>Continuous:</b> urinary fistulas, ectopic ureter</li><li><b>Nocturnal enuresis:</b> loss during sleep</li><li><b>Pharmacologic:</b> diuretics, anticholinergics, TCA (imipramine), alpha-blockers (doxazosin, tamsulosin)</li><li><b>Transient (reversible):</b> delirium, psychological, excessive urine output, stool impaction</li></ul>"},
 {"cat":"Incontinence","q":"What are the consequences and consequences of stress incontinence risk factors?",
  "a": "Consequences: UTI, depression/poor self-esteem, restricted activity, falls and fractures, negative effect on sexual activity/relationships. Stress incontinence risk factors: obesity, pregnancy, vaginal delivery/obstructed labor, menopause, chronic cough/constipation, smoking, prior pelvic surgery."},
 {"cat":"Incontinence","q":"How is urinary incontinence evaluated?",
  "a": "History; physical exam (vaginal: look for prolapse/rectocele/enterocele, pelvic floor strength; bladder full and empty); labs (urinalysis); US with <b>post-void residual</b>; lateral cystogram (vesicourethral junction opposite lower third of pubic bone, moves 0.5–1.5 cm with straining); <b>micturition diary</b>; dye tests (methylene blue in bladder + vaginal tampon for vesicovaginal fistula; phenazopyridine to confirm leakage is urine); urodynamics (filling pressure, sensation, involuntary contractions, capacity, compliance); cystourethroscopy."},
 {"cat":"Incontinence","q":"Outline the treatment ladder for urinary incontinence.",
  "a": "Lifestyle/behavioural modification (↓ caffeine/alcohol, weight loss, programmed voiding, bladder retraining) → <b>pelvic floor muscle training (first-line for stress/mixed)</b> → oral agents (α-adrenergic agonists, imipramine, anticholinergics, estrogen, SNRIs) → pessaries/vaginal inserts → urethral bulking agents → surgery: <b>midurethral sling</b>, colposuspension (Burch), artificial urinary sphincter, urine diversion."},
 {"cat":"BPH","q":"Describe the anatomy of the prostate and where BPH arises.",
  "a": "~70% glandular / 30% fibromuscular; normal weight 18 g; 3×4×2 cm; traversed by prostatic urethra. McNeal zones: peripheral (~70% of glandular part), central (~25%), <b>transition zone + periurethral glands — where BPH arises</b>."},
 {"cat":"BPH","q":"Give the epidemiology and heredity of BPH.",
  "a": "Most common benign tumor in men. Pathological incidence ~30% above 40 y; clinical ~40% above 50 y, increasing 10% per decade. Heredity: autosomal dominant in ~50% of men having prostatectomy for BPH before 60 y (only ~9% after 60 y). Obesity ↑ risk; exercise ↓ risk."},
 {"cat":"BPH","q":"Describe the pathophysiology cascade of BPH.",
  "a": "1. Prostate obstruction (lateral/median/three lobes/small fibrous type) → 2. Urethral obstruction (compression + elongation of prostatic urethra) → 3. Bladder changes (compensatory detrusor hypertrophy → decompensation: atrophy, saccules, diverticula) → 4. Upper tract dilatation (ureter &amp; kidney) — the endpoint of chronic obstruction."},
 {"cat":"BPH","q":"What are the obstructive and irritative symptoms of BPH?",
  "a": "<b>Obstructive:</b> hesitancy, weak stream, forked/intermittent stream, post-micturition dribbling. <b>Irritative:</b> urgency, frequency (nocturia first), precipitancy, urge incontinence. <b>AUA score:</b> 0–7 mild, 8–19 moderate, 20–35 severe (7 questions: frequency, urgency, nocturia, weak stream, intermittent micturition, straining, incomplete emptying)."},
 {"cat":"BPH","q":"List the complications of BPH.",
  "a": "STASIS → INFECTION → STONE FORMATION → HEMATURIA → ACUTE RETENTION → CHRONIC RETENTION → CHRONIC RETENTION WITH OVERFLOW → RENAL FAILURE. (Stasis begets infection and stones; retention follows; renal failure is the ultimate threat.)"},
 {"cat":"BPH","q":"Summarize medical therapy of BPH.",
  "a": "<b>Alpha-adrenergic blockers</b> (alfuzosin, doxazosin; α-1 selective: tamsulosin, silodosin) — relax bladder neck/prostate muscle, work quickly, best for small prostates. <b>5-α-reductase inhibitors</b> (finasteride, dutasteride) — block T→DHT, shrink prostate ~25%, take 3–6 months. PDE5 inhibitors also used. Watchful waiting: avoid cold, excess fluids, sexual excitement, and certain drugs (diuretics, antispasmodics, α-stimulants)."},
 {"cat":"BPH","q":"What is the surgical therapy of BPH?",
  "a": "<b>TURP — gold standard</b> (unipolar or bipolar); TUIP for small fibrous glands; transurethral laser prostatectomy (vaporization/enucleation); microwave hyperthermia; TUNA; HIFU; intraurethral stents; balloon dilation; <b>open prostatectomy</b> (transvesical/retropubic) for large glands."},
 {"cat":"Infertility","q":"Define male infertility and give its epidemiology.",
  "a": "Inability to conceive after <b>1 year of unprotected intercourse</b>. 15% of couples are infertile after one year: 40% male factor, 40% female factor, 20% both. Testis function: endocrine (testosterone — 2% free, 98% bound to SHBG) and exocrine (sperm). Axis: GnRH → FSH (spermatogenesis) + LH (testosterone)."},
 {"cat":"Infertility","q":"Classify the causes of male infertility.",
  "a": "<b>Pre-testicular (hormonal):</b> Kallmann syndrome, isolated LH/FSH deficiency, pituitary insufficiency, hyperprolactinemia, exogenous hormones. <b>Testicular:</b> Klinefelter, Noonan, myotonic dystrophy, vanishing testis, Sertoli-cell-only, Y-microdeletion, gonadotoxins, systemic disease, cryptorchidism, varicocele, orchitis/torsion, idiopathic. <b>Post-testicular:</b> obstruction (congenital absent vas, vasectomy, epididymal obstruction, infection), sperm-motility disorders (immotile cilia), disorders of coitus (impotence, hypospadias)."},
 {"cat":"Infertility","q":"Give the WHO (5th ed) semen analysis reference values.",
  "a": "Semen volume ≥<b>1.5 mL</b>; total sperm number ≥<b>39×10⁶</b>/ejaculate; concentration ≥<b>15×10⁶/mL</b>; total motility ≥<b>40%</b>; progressive motility ≥<b>32%</b>; vitality ≥<b>58%</b>; normal morphology ≥<b>4%</b>. Collection after 48–72 h abstinence; seminal fructose reflects seminal vesicles."},
 {"cat":"Infertility","q":"What are the surgical treatments for male infertility?",
  "a": "Varicocelectomy; vasovasostomy/epididymovasostomy (obstruction); TURED (ejaculatory duct obstruction); electroejaculation (spinal cord injury); sperm aspiration (vas/epididymis/testis) for ART; orchidopexy at 12–18 months; remove a gangrenous testis after torsion (sympathetic orchidopathia — immunologic damage to the contralateral testis)."},
 {"cat":"ED","q":"Define erectile dysfunction and list its risk factors.",
  "a": "Persistent inability to attain and maintain an erection sufficient for satisfactory sexual performance. Prevalence 10–20% of adult males; ↑ with age (1–10% &lt;40 y; 50–100% at 70–90 y). Risk factors: age, DM, cardiovascular disease, hypertension, smoking, overweight. <b>ED predicts future cardiovascular events.</b>"},
 {"cat":"ED","q":"Classify the etiology of ED.",
  "a": "<b>Psychogenic:</b> life stressors, performance anxiety. <b>Vasculogenic:</b> atherosclerosis, HTN, diabetes, pelvic radiotherapy. <b>Neurogenic:</b> diabetes, stroke, spinal trauma, pelvic/urethral surgery. <b>Hormonal:</b> hypogonadism, panhypopituitarism. <b>Drug-induced:</b> thiazides, β-blockers, antidepressants, antiandrogens, recreational drugs. <b>Anatomical:</b> Peyronie's disease, penile fracture."},
 {"cat":"ED","q":"How is ED diagnosed?",
  "a": "History (IIEF questionnaire, onset, comorbidities); labs — fasting glucose, lipid profile, <b>morning total testosterone</b> (if low → free testosterone, LH, prolactin); focused exam (genital, prostate, signs of hypogonadism, CVS/neuro); advanced workup (intracavernosal injection test, duplex US, nocturnal penile tumescence) if needed."},
 {"cat":"ED","q":"Outline ED management.",
  "a": "Treat curable causes (hypogonadism, psychogenic); lifestyle modification. <b>First-line: PDE5 inhibitors</b> (sildenafil, tadalafil, avanafil, vardenafil) — inhibit cGMP breakdown → vasodilation of cavernosal tissue; side effects headache/flushing/nasal congestion; <b>contraindicated with organic nitrates (severe hypotension)</b>. Second-line: topical/intracavernosal <b>alprostadil</b> (effective in 70%; priapism 1%), vacuum erection devices. Definitive: <b>penile prosthesis</b>."},
 {"cat":"PE","q":"Define premature ejaculation (ISSM 2014) and classify it.",
  "a": "1. Ejaculation always/nearly always before or within <b>~1 minute</b> of vaginal penetration (lifelong) or a clinically significant reduction to ~3 minutes or less (acquired); 2. inability to delay ejaculation; 3. negative personal consequences (distress, avoidance). Prevalence 5–30%. <b>Lifelong</b> (from first encounter) vs <b>acquired</b> (after prior normal function — examine for urethritis/prostatitis, hyperthyroidism)."},
 {"cat":"Urethritis","q":"List the causes of urethritis (gonococcal vs non-gonococcal).",
  "a": "<b>Gonococcal:</b> Neisseria gonorrhoeae (5–20%). <b>Non-gonococcal:</b> Chlamydia trachomatis (15–40%), Mycoplasma genitalium (15–25%), Trichomonas vaginalis, Ureaplasma urealyticum, HSV, adenovirus. N. gonorrhoeae: gram-negative intracellular diplococcus; incubation 3–14 days; males — purulent discharge/dysuria; females — often asymptomatic → PID/tubal scarring."},
 {"cat":"STDs","q":"What are the causes of genital ulcers?",
  "a": "Herpes simplex virus, syphilis (Treponema pallidum), chancroid (Haemophilus ducreyi), donovanosis. <b>HSV:</b> painful papules → vesicles → ulcers; diagnosis by PCR/culture from ulcer base; treatment acyclovir 400 mg tid × 7–10 days (or valacyclovir, famciclovir). <b>Chancroid:</b> painful ulcers + lymphadenitis → bubo; treat azithromycin 1 g single dose or ceftriaxone 250 mg IM."},
 {"cat":"STDs","q":"Describe the four stages of syphilis and its diagnosis.",
  "a": "Primary: painless single indurated chancre + regional lymphadenopathy (incubation 10–90 days). Secondary: bacteremia 3–5 months later (rash). Latent: seroreactivity without clinical disease. Tertiary (~35% of late latent): neurosyphilis, cardiovascular syphilis, gummatous syphilis. Diagnosis: <b>non-treponemal (VDRL, RPR — screening)</b> + <b>treponemal (FTA-ABS, TP-PA — confirm)</b>. Treatment: <b>IV penicillin G for all stages</b>."},
 {"cat":"STDs","q":"Summarize HPV and HIV key facts.",
  "a": "<b>HPV:</b> dsDNA virus; <b>types 6 &amp; 11 — non-oncogenic, ~90% of anogenital warts</b>; types 16 &amp; 18 — cervical/other anogenital cancers. <b>HIV:</b> retrovirus infecting T cells; spread via blood, semen, vaginal fluid, breast milk; progressive loss of CD4 T-lymphocytes; diagnosis by ELISA + Western blot confirmation; stages — acute (2–4 weeks, flu-like, tests often negative) → clinical latency → AIDS."},
]

# ============================================================
# GROUP 04 — Basics & Renal
# ============================================================
basics = [
 {"cat":"Anatomy","q":"Describe the embryology of the kidney (three stages).",
  "a": "<b>Pronephros</b> — rudimentary, non-functional (nephrotomes). <b>Mesonephros</b> — functional intermediate kidney (mesonephric tubules + Wolffian duct). <b>Metanephros</b> — the definitive kidney: <b>ureteric bud</b> (from mesonephric duct) + <b>metanephrogenic blastema</b>. Ureteric bud → collecting system (calyces, pelvis, ureter); blastema → nephrons. Cloaca receives allantois, hindgut, mesonephric ducts."},
 {"cat":"Anatomy","q":"Give the position, size and internal structure of the kidney.",
  "a": "Obliquely along psoas; right kidney lower than left (liver); ~150 g, 12×6×3 cm; T12–L3, hilum at L1; ~1 million nephrons. Internal: outer cortex, inner medulla with medullary pyramids → each opens into a minor calyx → 3 major calyces → renal pelvis → ureter."},
 {"cat":"Anatomy","q":"What is the order of structures at the renal hilum (anterior to posterior)?",
  "a": "<b>Renal vein (anterior) → renal artery → renal pelvis (posterior)</b>. Gerota's (renal) fascia encloses the kidney with its fibrous and fatty capsules; medially the left and right fascia blend anterior to the aorta and IVC."},
 {"cat":"Anatomy","q":"What are the relations, blood supply and lymphatics of the kidneys?",
  "a": "Arterial: renal arteries from aorta at L1/L2; enter hilum as 5 segments (apical, upper, middle, lower — anterior; posterior) that <b>do not communicate</b>. Venous: renal veins unite into 5 vessels; left renal vein crosses anterior to aorta (receives left adrenal + gonadal veins). Posterior relations: diaphragm, pleura, lower ribs, psoas, quadratus lumborum, transversus abdominis. Anterior: right — suprarenal, liver, 2nd part duodenum, right colic flexure; left — suprarenal, stomach, spleen, pancreas, left colic flexure, jejunum."},
 {"cat":"Anatomy","q":"Describe the ureter course and its key relations.",
  "a": "Continues from the renal pelvis at L1; ~25 cm long; crosses the pelvic brim at the SIJ anterior to the external iliac artery; runs anterior to internal iliac; in females the uterine artery crosses the juxtavesical ureter; in males the vas deferens crosses anterior to it. Landmarks: UPJ and UVJ (the UVJ's oblique intramural course = anti-reflux mechanism)."},
 {"cat":"Anatomy","q":"Describe the bladder structure, trigone and innervation.",
  "a": "Hollow muscular reservoir, capacity 400–500 mL; layers: mucosa (urothelium), submucosa, muscle (detrusor — inner longitudinal, middle circular, outer deep longitudinal), perivesical fat, peritoneum. <b>Oblique intramural ureter = anti-reflux mechanism</b>. Innervation: pelvic nerves (sensation + parasympathetic contraction), pudendal (voluntary external sphincter), sympathetic (storage). Arteries: superior/middle/inferior vesical from internal iliac."},
 {"cat":"Anatomy","q":"Describe the anatomy of the prostate and scrotum/spermatic cord.",
  "a": "Prostate: ~20 g, below the bladder; contains the posterior urethra (~2.5 cm); ejaculatory ducts open at the verumontanum; Lowsley 5 lobes vs McNeal zones (peripheral, central, transition). Spermatic cord contents: ductus deferens (45 cm), testicular artery, pampiniform plexus, nerves, lymphatics; coverings from the layers of the abdominal wall through which the testis descended (processus vaginalis). <b>Left spermatic vein → left renal vein (basis of left varicocele and renal tumor association)</b>; testicular lymphatics → lumbar nodes (testicular cancer metastasizes retroperitoneally, not inguinally)."},
 {"cat":"Anomalies","q":"Describe renal agenesis — bilateral and unilateral.",
  "a": "<b>Bilateral:</b> complete absence of kidneys and ureters — peculiar face, pulmonary abnormalities, single umbilical artery; failure of ureteric bud or blastema; <b>incompatible with life</b>. <b>Unilateral:</b> more common; compatible with life if the solitary kidney is intact. IVU DDx: ectopic kidney, non-visualized/obstructed kidney, renal failure (no contrast excretion), prior nephrectomy."},
 {"cat":"Anomalies","q":"Compare adult (AD) and infantile (AR) polycystic kidney disease.",
  "a": "<b>Adult (ADPKD):</b> autosomal dominant, more common; identified 30–50 y; renal mass, flank pain, hematuria, UTIs, late renal insufficiency. <b>Infantile (ARPKD):</b> autosomal recessive, rare; small cysts = generalized dilatation of collecting tubules; 4 types (perinatal, neonatal, infantile, juvenile); the earlier the age, the worse the prognosis; bilateral, pulmonary hypoplasia, oliguria, hypertension; often death at birth."},
 {"cat":"Anomalies","q":"Differentiate renal ectopia from ptosis; what is the commonest fusion anomaly?",
  "a": "<b>Ectopia:</b> kidney never reaches the renal fossa (pelvic, iliac, abdominal, thoracic, crossed) — pelvis anterior, ureter short. <b>Ptosis:</b> normally positioned kidney that descends with posture — pelvis remains anterior. <b>Horseshoe kidney</b> — the commonest fusion anomaly — is often complicated by UPJ obstruction and stone disease."},
 {"cat":"Anomalies","q":"List ureteral anomalies and their features.",
  "a": "<b>Ureteral duplication:</b> complete (two pelves, two ureters, two orifices) or incomplete ('Y' junction); ectopic ureter may open into vagina/urethra in females. <b>Ureterocele:</b> cystic ballooning of the distal ureter — 'cobra head' on pyelography. <b>UPJO:</b> stenosis, aberrant vessels, aganglionic segments — <b>commonest congenital cause of hydronephrosis in children</b>. <b>Retrocaval ureter:</b> ureter behind the IVC."},
 {"cat":"Anomalies","q":"Describe bladder exstrophy, posterior urethral valve and hypospadias.",
  "a": "<b>Bladder exstrophy:</b> complete — wide separation of pelvic bones, epispadias, rudimentary penis/scrotum (cleft clitoris in girls); incomplete — defects only in abdominal/bladder wall. <b>PUV:</b> exaggerated folds of posterior urethra → bilateral hydronephrosis + retention; diagnosed by VCUG (MCU); most common cause of bladder outlet obstruction in boys. <b>Hypospadias:</b> abnormal ventral meatus + chordee; <b>never circumcise</b> — the prepuce is used for repair; surgery at 6–18 months."},
 {"cat":"Anomalies","q":"What are dystopic vs ectopic testis and the treatment of cryptorchidism?",
  "a": "<b>Dystopic:</b> stopped along the normal path of descent (e.g., inguinal canal). <b>Ectopic:</b> outside the normal path — femoral, perineal, penile, <b>superficial inguinal pouch (most common)</b>. Risks of undescended testis: malignant change, infertility, torsion, trauma. Treatment: hormonal (hCG) and/or surgery <b>before the age of one year</b>."},
 {"cat":"Investigations","q":"What does the microscopic urine examination tell us?",
  "a": "RBC casts → glomerulonephritis; WBC casts → infection/pyelonephritis; cellular casts → ATN; protein casts → interstitial nephritis; <b>bacteria ≥5/hpf = ≥10⁵ cfu/mL (significant bacteriuria)</b>; crystals (oxalate, uric acid, struvite, cystine); parasites (bilharziasis, trichomonas)."},
 {"cat":"Investigations","q":"What is creatinine clearance and its normal values?",
  "a": "eGFR = Ucr × V / Pcr (urine creatinine × urine volume ÷ plasma creatinine). Normal GFR <b>90–120 mL/min</b>; serum creatinine adult 0.4–1.4 mg/dL, children 0.2–0.7 mg/dL. A rise in creatinine indicates damage to a significant number of nephrons."},
 {"cat":"Investigations","q":"Summarize PSA — nature, values, factors and derivatives.",
  "a": "34-kD glycoprotein produced by prostatic epithelial cells; liquefies ejaculate; in blood 75% bound / 25% free; blood level normal &lt;4 ng/mL (age-specific). Increases with: prostatitis, prostate cancer, enlarged prostate, catheterization/instrumentation, biopsy. Derivatives: free/total ratio, <b>PSA velocity &gt;0.75 ng/mL/yr</b>, PSA density (cutoff ≥0.15 ng/mL/gram), age-specific PSA. Uses: screening + follow-up after treatment."},
 {"cat":"Investigations","q":"What are the phases and uses of IVU?",
  "a": "Uses: obstruction (UPJO, strictures), hematuria, recurrent UTIs, stone disease, fistulas. Phases: plain film (KUB/scout) → nephrogram → urogram (supine after 5–10 min) → prone film → full-bladder film. Use has diminished with cross-sectional imaging (CT/MRI)."},
 {"cat":"Investigations","q":"What does the VCUG demonstrate?",
  "a": "Bladder capacity (contracted bladder); shape (diverticulum, neurogenic 'Christmas tree' bladder); filling defects (tumors, ureteroceles); emptying; <b>posterior urethral valve (ballooning/keyhole sign)</b>; <b>vesicoureteric reflux</b>. Ascending urethrogram: retrograde contrast for urethral strictures/injuries."},
 {"cat":"AKI","q":"Give the AKI diagnostic criteria and KDIGO stages.",
  "a": "Diagnosis: ↑ creatinine ≥0.3–0.5 mg/dL within 48 h; ↑ ≥1.5× baseline within 7 days; urine output ≤0.5 mL/kg/h for 6 h; GFR ↓25%. <b>KDIGO:</b> I — Cr ↑≥0.3 mg/dL or UOP &lt;0.5 mL/kg/h ×6 h; II — Cr 2–2.9× baseline or UOP &lt;0.5 ×12 h; III — Cr ≥3× or ≥4 mg/dL, UOP &lt;0.3 ×24 h/anuria 12 h, <b>or initiation of RRT</b>. Staging by the worst criterion."},
 {"cat":"AKI","q":"Give the aetiology percentages of AKI.",
  "a": "<b>Pre-renal 55%</b> (hypovolemia, ↓cardiac output, drugs affecting autoregulation — NSAIDs, ACE-I/ARBs, cyclosporin). <b>Intrinsic 40%</b> (glomerular, tubular/interstitial — ischemia/sepsis/nephrotoxins, vascular — vasculitis/TTP-HUS/malignant HTN). <b>Post-renal 5%</b> (obstruction — the most surgically remediable). Risk factors: age &gt;75, pre-existing CKD/cardiac/hepatic disease, DM, nephrotoxins."},
 {"cat":"AKI","q":"What is pre-renal azotemia and its hallmark?",
  "a": "Transient renal hypoperfusion → ↓GFR with urinary sodium retention; <b>hallmark = reversibility</b> with treatment of the cause (no structural damage); 'gold standard' = response to fluid repletion with return of renal function within 24–72 h. Sustained pre-renal azotemia → ATN."},
 {"cat":"AKI","q":"What are the causes and prevention of ATN?",
  "a": "Causes: renal hypoperfusion/ischemia (most common) and nephrotoxins — aminoglycosides (10–30% risk), amphotericin B, cisplatin, cyclosporin, temsirolimus. Prevention: single daily-dose aminoglycosides, monitor levels, avoid prolonged therapy. AGN = RBC casts; AIN = WBC casts + eosinophiluria (Hansel stain); ATN = muddy brown casts."},
 {"cat":"AKI","q":"When should you refer AKI to a nephrologist within 24 hours?",
  "a": "1. Suspected specialist diagnosis (vasculitis, GN, tubulointerstitial nephritis, myeloma); 2. AKI with no clear cause; 3. inadequate response to treatment/complications; 4. AKI stage 3; 5. renal transplant patient; 6. CKD stage 4 or 5. Urologists exclude/relieve obstruction — the only truly reversible cause."},
 {"cat":"AKI","q":"What are the indications for immediate dialysis in AKI?",
  "a": "Refractory hyperkalemia (&gt;7 mmol/L or ECG changes); severe metabolic acidosis (pH &lt;7.15); refractory pulmonary edema; pericarditis; symptomatic uremia (especially encephalopathy); BUN &gt;150 mg/dL (or rapidly rising); certain intoxications/dialyzable toxins."},
 {"cat":"AKI","q":"How is calcular anuria managed, and how do you distinguish AKI from CKD?",
  "a": "Calcular anuria: CT (non-contrast, gold standard for renal colic) → <b>bypass obstruction with JJ stent or nephrostomy</b> → definitive stone management when stable. AKI vs CKD: history of elevated creatinine (old records), <b>small shrunken kidneys</b>, normocytic normochromic anemia, renal osteodystrophy, and secondary hyperparathyroidism favor CKD."},
 {"cat":"CKD","q":"Define CKD, GFR and the Cockcroft-Gault formula.",
  "a": "Kidney damage or GFR &lt;60 ml/min/1.73 m² persisting ≥3 months. Glomeruli filter ~180 L/day (~125 mL/min); normal GFR ≈120 ml/min/1.73 m²; declines ~1 ml/min/year after the third decade. <b>Cockcroft-Gault:</b> GFR = (140 − age) × weight(kg) / (72 × serum creatinine); ×0.85 for females."},
 {"cat":"CKD","q":"Give the etiologies of ESRD and the KDIGO GFR categories.",
  "a": "Etiologies: DM 38%, hypertension 25%, glomerulonephritis 14%, cystic kidney disease 5%, urologic 2%, unknown/other 15%. KDIGO: <b>G1 ≥90; G2 60–89; G3a 45–59; G3b 30–44; G4 15–29; G5 &lt;15 (kidney failure/ESRD)</b>."},
 {"cat":"CKD","q":"What are the management steps to slow CKD progression?",
  "a": "1. Treat underlying cause; 2. manage acute deterioration (reversible: decreased perfusion, nephrotoxins, obstruction); 3. <b>slow progression</b> — strict BP control, reduce proteinuria, tight glycemic control, dietary protein restriction 0.6–0.8 g/kg/day; 4. treat metabolic/systemic complications; 5. prepare for RRT."},
 {"cat":"CKD","q":"What are the BP targets (NICE 2014) and drugs of choice for proteinuria?",
  "a": "Targets: CKD alone &lt;140/90; <b>CKD + diabetes &lt;130/80; CKD + proteinuria &lt;130/80</b> (with ACR ≥30 mg/mmol). Drugs of choice: <b>ACE inhibitors and ARBs first-line for proteinuria; never combine ACE + ARB</b>; second-line non-dihydropyridine CCBs (diltiazem, verapamil); salt restriction."},
 {"cat":"CKD","q":"How is anemia in CKD treated?",
  "a": "Causes: relative EPO deficiency, ↓RBC survival, bleeding/iron deficiency, SHPT (marrow fibrosis), inflammation, hemoglobinopathies, vitamin deficiencies. Treatment: <b>maintain Hb 10.5–12 g/dL</b> with iron ± erythropoiesis-stimulating agents (rHuEPO, darbepoetin), after excluding other causes."},
 {"cat":"Transplant","q":"What are the indications for native nephrectomy before transplantation?",
  "a": "Symptomatic renal stones not cleared by minimally invasive therapy; high-grade solid renal tumors (± acquired cystic disease); symptomatic/infected polycystic kidneys or those with solid tumors; persistent anti-GBM antibodies; significant proteinuria uncontrolled medically; recurrent pyelonephritis; grade 4–5 VUR with UTIs. Ideally ≥6 weeks before transplant."},
 {"cat":"Transplant","q":"Describe the transplant surgical procedure and function outcomes.",
  "a": "Wet ischemia time ≤30 min; kidney placed extraperitoneally in the lower quadrant; renal artery → internal/external iliac artery; vein → iliac vein; ureter → bladder. Living donor: immediate function; delayed graft function ~30% of cadaveric (prolonged cold ischemia) — dialysis until graft works. Graft survival: living 95%/76% (1/5 y); cadaveric 89%/61%. Patient survival: living 98%/91%; cadaveric 95%/81%."},
 {"cat":"Transplant","q":"List the surgical complications of renal transplantation.",
  "a": "1. <b>Acute vascular occlusion</b> (0.5–8%, first week; renal vein thrombosis — graft tenderness, dark hematuria, ↓urine; Doppler US/isotope scan; surgery). 2. <b>Peritransplant hematoma</b>. 3. <b>Lymphocoele</b> (5–15%, first 3 months; percutaneous drainage). 4. <b>Obstructive uropathy</b> (3–6%; extrinsic compression/technical; US hydronephrosis; surgical). 5. <b>Renal artery stenosis</b> (late; uncontrolled HTN, graft dysfunction; US/MRA). 6. Urine leak at ureterovesical anastomosis."},
 {"cat":"Transplant","q":"What is the immunosuppressive regimen and how is rejection treated?",
  "a": "Lifelong 'triple' therapy: <b>calcineurin inhibitor (cyclosporine/tacrolimus) + antiproliferative (mycophenolate mofetil/azathioprine) + corticosteroids</b>; sirolimus in standard protocols. Acute rejection: IV corticosteroids (methylprednisolone 250–1000 mg/day ×3 days). Fever in the 1st month is usually post-op infection (pneumonia, wound, line sepsis, catheter UTI); macrolides require ↓ cyclosporine/tacrolimus/sirolimus doses."},
]

# ============================================================
# GROUP 05 — Urological Trauma
# ============================================================
trauma = [
 {"cat":"Overview","q":"What are the initial management principles of urological trauma?",
  "a": "~10% of ER injuries involve the GU system. Control hemorrhage/shock + resuscitation; IV lines; <b>examine the urethral meatus for blood BEFORE passing a urethral catheter in men</b>; detailed history (type/calibre of weapon in gunshot wounds); examine abdomen/genitalia for contusions or subcutaneous hematomas suggesting deep injury."},
 {"cat":"Renal","q":"Give the epidemiology and classification (grades) of renal injuries.",
  "a": "Renal injuries are the most common urinary system injuries; <b>blunt trauma 80–85%</b>; pathological kidneys (hydronephrosis, tumors) rupture more easily. Grades: <b>1 — contusion (most common); 2 — cortical laceration, small perirenal hematoma; 3 — deeper laceration; 4 — ... ; 5 — pedicle avulsion/shattered kidney</b>. The degree of hematuria does NOT correspond to injury severity."},
 {"cat":"Renal","q":"How are renal injuries staged and when is imaging indicated?",
  "a": "<b>CT is the gold standard</b> for staging — lacerations, extravasation, hematoma extent, nonviable tissue, associated organ injury. IVP if CT unavailable. Indications: any hematuria after trauma; flank stab/gunshot wounds even without hematuria; rapid deceleration (vascular injury may have NO hematuria). <b>Non-visualization on IVU:</b> pedicle avulsion, arterial thrombosis, severe contusion with vascular spasm, absent kidney."},
 {"cat":"Renal","q":"What are the complications of renal trauma?",
  "a": "Early: <b>hemorrhage</b> (most important — heavy retroperitoneal bleeding → collapse). Late: hypertension, hydronephrosis, arteriovenous fistula, calculus formation, pyelonephritis, renal atrophy. Follow-up: monitor BP for months; excretory urography at 3–6 months."},
 {"cat":"Renal","q":"How are renal injuries treated?",
  "a": "Minor blunt injuries (85%) — conservative: bed rest, hydration, observe. <b>Surgery</b> for: persistent retroperitoneal bleeding, urinary extravasation, nonviable parenchyma, renal pedicle injuries (&lt;5% of injuries). <b>Penetrating injuries are surgically explored</b> (exception: complete staging shows only minor parenchymal injury)."},
 {"cat":"Ureter","q":"When does ureteral injury occur and what is its pathogenesis?",
  "a": "Rare: difficult pelvic surgery (ligation/cut), endoscopic basket manipulation, gunshot wounds, rapid deceleration (avulsion from pelvis). <b>Partial division — early:</b> urinary extravasation, ileus/peritonitis, urinoma; <b>late:</b> ureterovaginal/ureterocutaneous fistula, fibrosis/stricture, hydronephrosis. <b>Bilateral complete ligation → anuria.</b> Prognosis excellent if diagnosed and corrected early."},
 {"cat":"Ureter","q":"How are ureteral injuries diagnosed?",
  "a": "Suspect with retroperitoneal stab/gunshot (mid-ureter most common site); fever, flank pain, ileus, watery discharge from wound/vagina (confirm by creatinine); IV indigo carmine appears blue in urine. Imaging: IVU (delayed excretion + hydronephrosis; extravasation), CTU/3D reconstruction, US (urinoma — best early post-op screen), radionuclide scan."},
 {"cat":"Ureter","q":"How are ureteral injuries treated?",
  "a": "Immediate re-exploration when recognized during surgery; delayed repair within 7–10 days if no infection/abscess; <b>percutaneous nephrostomy</b> if recognized late or complicated. Goals: complete debridement, tension-free spatulated anastomosis, watertight closure, ureteral stenting, drainage."},
 {"cat":"Bladder","q":"Describe the pathogenesis and clinical findings of bladder rupture.",
  "a": "~15% of pelvic fractures have bladder/urethral injury; <b>pelvic fracture accompanies bladder rupture in 90%</b>. Fracture fragments perforate → <b>extraperitoneal rupture</b>; direct blow to a full bladder → <b>intraperitoneal rupture</b>. Clinical: inability to void, gross hematuria, pelvic/lower abdominal pain, hemorrhagic shock (pelvic venous disruption), acute abdomen with intraperitoneal rupture, indistinct rectal landmarks from pelvic hematoma."},
 {"cat":"Bladder","q":"Describe the ascending cystogram technique and findings.",
  "a": "Fill bladder with 300 mL contrast → drain completely → take a second film. Demonstrates extraperitoneal extravasation (may not appear on filling film) and <b>intraperitoneal extravasation (free contrast in the abdomen)</b>. Complications: pelvic abscess (extraperitoneal rupture + infected hematoma), delayed peritonitis (intraperitoneal), partial incontinence (bladder neck injury)."},
 {"cat":"Bladder","q":"How is bladder rupture treated?",
  "a": "<b>Extraperitoneal:</b> urethral catheter drainage alone usually suffices (~10 days). <b>Intraperitoneal:</b> surgical repair via transperitoneal approach — close perforations, close peritoneum carefully, close bladder in layers with absorbable suture, evacuate all extravasated fluid; suprapubic cystostomy left in place; avoid entering the lateral pelvic hematoma. Prognosis excellent; catheter removed ~10 days."},
 {"cat":"Urethra","q":"What are the anatomic divisions of the urethra and how do they relate to injury?",
  "a": "<b>Posterior urethra</b> = prostatic + membranous portions — injured by <b>pelvic fractures</b> (membranous urethra sheared from the prostatic apex). <b>Anterior urethra</b> = bulbous + pendulous portions — injured by <b>straddle falls</b>. <b>Blood at the urethral meatus is the single most important sign of urethral injury</b>."},
 {"cat":"Urethra","q":"What are the dangers of passing a catheter in posterior urethral injury?",
  "a": "May infect the periprostatic/perivesical hematoma and convert an incomplete laceration into a complete one. Management: treat shock/hemorrhage; <b>avoid urethral catheterization</b>; <b>suprapubic cystostomy</b> for 3 months; incomplete laceration heals spontaneously (catheter removed 2–3 weeks after no extravasation on VCUG); delayed reconstruction after 3 months."},
 {"cat":"Urethra","q":"Compare primary repair vs delayed reconstruction for posterior urethral injury.",
  "a": "<b>Stricture:</b> ~50% (primary) vs ~5% (delayed). <b>Impotence:</b> 30–80% mean ~50% vs 30–35%. <b>Incontinence:</b> one-third vs &lt;5%. <b>Delayed reconstruction after suprapubic drainage dramatically reduces all three complications.</b>"},
 {"cat":"Urethra","q":"Describe anterior urethral injury — pathogenesis and complications.",
  "a": "Straddle injury or instrumentation; contusion (perineal hematoma, resolves) vs laceration (urine extravasation limited by <b>Colles' fascia</b> — extends into scrotum, penile shaft, abdominal wall → sepsis). Complications: bleeding (corpus spongiosum; local pressure), infection/sepsis (debridement + drainage), <b>stricture</b> (common; often mild). Management: suprapubic cystostomy; voiding study at 7 days (minor) or 2–3 weeks (extensive); extensive extravasation → immediate repair."},
]

ALL_URO = [
    ("01_Uro-oncology", "Uro-Oncology", uro_onco),
    ("02_Stones_and_Infections", "Stones & Infections of the Urinary Tract", stones),
    ("03_Functional_and_Andrology", "Functional Urology & Andrology", functional),
    ("04_Basics_and_Renal", "Basics of Urology & Renal Medicine", basics),
    ("05_Urological_Trauma", "Urological Trauma", trauma),
]
