# -*- coding: utf-8 -*-
"""Internal Medicine (Nephrology) flashcard content — source: slide decks."""

# ============================================================
# GROUP 01 — Glomerular Diseases
# ============================================================
glomerular = [
 {"cat":"Principles","q":"Define a glomerulopathy (glomerular disease).",
  "a":"A group of glomerular disorders characterized by: <b>Clinically</b> — one or more of 5 cardinal features; <b>Pathologically</b> — involvement of <b>both kidneys symmetrically</b>; <b>Etiologically</b> — unknown (primary/idiopathic) or secondary to various causes."},
 {"cat":"Principles","q":"What are the five cardinal clinical features of glomerular disease?",
  "a":"<ul><li>1. <b>Proteinuria</b></li><li>2. <b>Hematuria</b></li><li>3. <b>Oliguria</b></li><li>4. <b>Hypertension</b></li><li>5. <b>Edema</b></li></ul>"},
 {"cat":"Principles","q":"How is glomerulonephritis classified etiologically?",
  "a":"<ul><li><b>Primary GN</b> — unknown cause (idiopathic)</li><li><b>Secondary GN</b> — secondary to: infections, multisystem diseases, malignancy/paraproteinemias, drugs &amp; toxins, metabolic causes (DM, gout), heredofamilial diseases, and others (sarcoidosis, pre-eclampsia, serum sickness…)</li></ul>"},
 {"cat":"Principles","q":"Give examples of infective causes of secondary GN (bacterial, viral, parasitic).",
  "a":"<ul><li><b>Bacterial:</b> streptococcal (β-hemolytic types 1, 4, 12, 49 → PSGN); non-streptococcal: staphylococci, gonococci, salmonella, meningococcal, secondary syphilis, leprosy</li><li><b>Viral:</b> HBV, HCV, HIV, EBV, mumps, measles, Coxsackie, varicella</li><li><b>Parasitic:</b> malaria, schistosomiasis, filariasis, toxoplasmosis</li></ul>"},
 {"cat":"Principles","q":"Which drugs & toxins can cause secondary GN?",
  "a":"Penicillin, heavy metals (mercury, gold), heroin, captopril, antivenom/antitoxins, and contrast media."},
 {"cat":"Principles","q":"List the heredofamilial causes of glomerular disease.",
  "a":"Thin basement membrane disease, Alport's syndrome, Fabry's disease, Nail-Patella syndrome, and sickle cell disease."},
 {"cat":"Principles","q":"What is the value of light microscopy (LM), electron microscopy (EM) and immunofluorescence (IF) on renal biopsy?",
  "a":"<ul><li><b>LM:</b> the histopathological type + severity/degree of disease</li><li><b>EM:</b> site of immune deposition — subendothelial, subepithelial, mesangial</li><li><b>IF:</b> type of immune deposition (e.g., IgA, C3, C4)</li></ul>"},
 {"cat":"Principles","q":"What IF patterns are seen in immune-complex GN vs anti-GBM disease?",
  "a": "<b>Immune-complex GN:</b> diffuse <span class='hl'>granular</span> deposits. <b>Anti-GBM antibody disease:</b> smooth <span class='hl'>linear</span> deposits."},
 {"cat":"Principles","q":"Describe the pathology of Minimal Change Disease (MCD).",
  "a":"<b>LM:</b> normal or mild mesangial cell increase. <b>EM:</b> fusion of foot processes of podocytes. <b>IF:</b> no deposits."},
 {"cat":"Principles","q":"What does light microscopy show in Membranous GN (MGN)?",
  "a":"Diffuse thickening of the glomerular basement membrane (GBM)."},
 {"cat":"Principles","q":"Distinguish FSGS from FSGN.",
  "a":"<b>FSGS</b> (Focal Segmental Glomerulosclerosis) = <b>sclerosis/scarring</b> of some segments in some glomeruli. <b>FSGN</b> (Focal Segmental GN) = <b>cellular proliferation</b> of some segments in some glomeruli."},
 {"cat":"Principles","q":"Name the 5 major clinical syndromes of glomerulopathy and one pathology/course highlight for each.",
  "a":"<ul><li><b>Acute GN (nephritic):</b> abrupt onset, hematuria/proteinuria/oliguria/edema/HTN; pathology DPGN; usually spontaneous resolution</li><li><b>Nephrotic syndrome:</b> proteinuria ≥3+, albumin &lt;2.5, hyperlipidemia, edema; variable lesions &amp; course</li><li><b>Chronic GN:</b> insidious, progressive decline in GFR → ESRD (common pathway)</li><li><b>RPGN:</b> rapid GFR decline, crescents — <b>renal emergency</b></li><li><b>Asymptomatic proteinuria ± hematuria:</b> accidentally discovered, relatively benign (FSGN)</li></ul>"},
 {"cat":"Principles","q":"Which urine findings strongly suggest glomerular origin of hematuria?",
  "a": "<b>Dysmorphic red cells</b> (phase-contrast microscopy) strongly suggest GN, and <b>red cell casts</b> are <span class='hl'>diagnostic of acute GN</span>."},
 {"cat":"Principles","q":"Give the specific investigation for: DM, recent streptococcal infection, SLE, Goodpasture disease, IgA nephropathy, low complement states.",
  "a": "<ul><li>DM → blood glucose</li><li>Streptococcal → ASOT + throat/skin swab</li><li>SLE → ANA &amp; anti-dsDNA</li><li>Goodpasture → anti-GBM antibody</li><li>IgA nephropathy (Berger) → serum IgA</li></ul>"},
 {"cat":"Principles","q":"List the conditions with decreased serum complement (C3).",
  "a": "<ul><li><b>Post-infection:</b> acute PSGN (transient, ~8 weeks), infective endocarditis, shunt nephropathy</li><li><b>SLE</b></li><li><b>Cryoglobulinemia</b></li><li><b>Serum sickness</b></li></ul>"},
 {"cat":"Principles","q":"Why do ACEIs/ARBs reduce proteinuria?",
  "a":"They block the vasoconstrictor effect of angiotensin II on the <b>efferent arteriole</b> → efferent vasodilation → ↓ intraglomerular pressure → ↓ GFR → ↓ filtered protein → <b>↓ proteinuria</b>. Note: use small doses in normotensive patients; use cautiously in renal failure &amp; hyperkalemia."},
 {"cat":"Principles","q":"What are the BP targets in renal disease according to proteinuria?",
  "a": "<ul><li>Proteinuria <b>&gt;1 gm/day</b> → target BP <b>&lt;125/75</b> (mean &lt;92)</li><li>Proteinuria <b>&lt;1 gm/day</b> → target BP <b>&lt;130/80</b> (mean &lt;98)</li></ul>First-line renoprotection: ACEIs/ARBs (also CCBs)."},
 {"cat":"Principles","q":"When is prophylactic anticoagulation used in nephrotic syndrome?",
  "a":"In nephrotic patients at high risk of thromboembolism: <b>albumin &lt;2.5 → risk of venous thrombosis → anticoagulants</b>; risk of arterial thrombosis → <b>aspirin</b>."},
 {"cat":"Principles","q":"What is the natural course of PSGN, IgA nephropathy/FSGS, MGN, and anti-GBM/ANCA crescentic GN?",
  "a": "<ul><li><b>PSGN:</b> tends to resolve completely; little risk of ESRD</li><li><b>IgA nephropathy &amp; FSGS:</b> indolent but persistent → renal failure</li><li><b>MGN:</b> unpredictable — may remit, persist/relapse, or progress over years</li><li><b>Anti-GBM &amp; ANCA crescentic GN:</b> rapid progression to ESRD <b>unless treated</b></li></ul>"},
 {"cat":"Acute GN","q":"Define acute GN (nephritic syndrome) — list its 5 features.",
  "a":"Acute onset of: <ul><li>1. <b>Hematuria</b> (macroscopic or microscopic)</li><li>2. <b>Proteinuria</b> &lt;3.5 gm/day/1.73 m² (non-nephrotic)</li><li>3. <b>Hypertension</b></li><li>4. <b>Edema</b></li><li>5. <b>Oliguria</b> &lt;300 ml/day in severe cases</li></ul>"},
 {"cat":"Acute GN","q":"Nephritic vs nephrotic: which is dominated by hematuria and which by proteinuria?",
  "a":"<b>Nephritic syndrome (acute GN):</b> dominated by <b>hematuria</b> with non-nephrotic proteinuria (&lt;3.5 gm/day). <b>Nephrotic syndrome:</b> dominated by <b>heavy proteinuria ≥3.5 gm/day</b>."},
 {"cat":"Acute GN","q":"Why does urine appear red vs smoky in acute GN?",
  "a":"<b>Red urine</b> → in alkaline urine. <b>Smoky/reddish-brown urine</b> → in acidic urine: denaturation of hemoglobin forms <b>acid haematine</b> and methemoglobin gives the smoky color."},
 {"cat":"Acute GN","q":"What are dysmorphic red cells and how are they best seen?",
  "a":"Small, distorted RBCs with low hemoglobin content due to mechanical injury while passing through damaged glomerular capillary walls — best seen by <b>phase contrast microscopy</b>."},
 {"cat":"Acute GN","q":"Why does edema develop early around the eyelids in acute GN?",
  "a":"Eyelids are an area of <b>low tissue pressure</b>. Edema results from salt &amp; water retention (↑ distal Na⁺ reabsorption + ↓ GFR → ↓ salt delivery to tubules)."},
 {"cat":"Acute GN","q":"Why is hypertension in acute GN called volume-dependent?",
  "a":"It is due to <b>salt &amp; water retention</b> (volume expansion), not a primary vasoconstrictor mechanism."},
 {"cat":"Acute GN","q":"List the indications for renal biopsy in acute GN.",
  "a": "<ul><li>A. Unusual clinical features</li><li>B. Uncertain diagnosis</li><li>C. <b>Rapid deterioration of renal function → crescentic GN</b></li></ul>"},
 {"cat":"Acute GN","q":"How is hypertensive encephalopathy in acute GN managed?",
  "a":"Maintain airway; control BP with a parenteral agent (e.g., <b>hydralazine 5–20 mg infusion</b>); control fits with IV diazepam (10 mg)."},
 {"cat":"Nephrotic","q":"Define nephrotic syndrome (4 criteria).",
  "a": "<ul><li>1. <b>Heavy proteinuria ≥3.5 gm/day/1.73 m²</b> (or UP/UCr ratio &gt;3.5 in adults)</li><li>2. <b>Hypoalbuminemia ≤2.5 gm/dl</b></li><li>3. <b>Edema</b></li><li>4. <b>Hyperlipidemia</b> (hypercholesterolemia)</li></ul>"},
 {"cat":"Nephrotic","q":"Blood pressure in nephrotic syndrome: MCD vs MCGN.",
  "a": "In <b>MCD</b> blood pressure is <span class='hl'>always normal</span>; in <b>MCGN</b> hypertension is <span class='hl'>always present</span>."},
 {"cat":"Nephrotic","q":"What lab findings characterize nephrotic syndrome?",
  "a": "<ul><li>24-h protein &gt;3.5 gm/day; albumin ≤2.5 gm/dl</li><li>Electrophoresis: ↓ albumin, ↑ alpha-2 &amp; beta globulins, ↑ fibrinogen</li><li>↑ cholesterol &amp; LDL; ↑ triglycerides in ~50%; normal/↓ HDL</li><li><b>Hypocalcemia</b> — urinary loss of cholecalciferol-binding protein</li><li>RFT usually normal (impaired in severe hypovolemia, MGN, MCGN)</li></ul>"},
 {"cat":"Nephrotic","q":"What is selective vs unselective proteinuria?",
  "a":"Ratio of clearance of a large protein (e.g., IgG) to a small protein (albumin/transferrin): <b>Low ratio → selective</b> (MCD, DM, renal amyloidosis); <b>High ratio → unselective</b> (e.g., crescentic GN). Tested in children."},
 {"cat":"Nephrotic","q":"When is renal biopsy NOT indicated in nephrotic syndrome?",
  "a": "<ul><li>Young children with selective proteinuria, normotensive, benign urinary sediment → likely MCD</li><li>Long-standing DM (&gt;10 y type 1, &gt;5 y type 2) with retinopathy/neuropathy</li><li>Patients on penicillamine-type drug therapy</li></ul>"},
 {"cat":"Nephrotic","q":"How do you manage thrombotic complications in nephrotic syndrome?",
  "a":"Long-term oral anticoagulant (warfarin). NB: <b>heparin is ineffective</b> because antithrombin III is lost in urine. Prophylactic anticoagulation is used in NS due to membranous GN (thromboembolism is common)."},
 {"cat":"Anti-GBM","q":"Differentiate Goodpasture disease from Goodpasture syndrome.",
  "a": "<b>Goodpasture disease:</b> kidney-limited — anti-GBM GN with circulating anti-GBM antibodies. <b>Goodpasture syndrome:</b> systemic — triad of anti-GBM GN + circulating antibodies + <b>pulmonary hemorrhage</b>."},
 {"cat":"Anti-GBM","q":"List the differential diagnosis of pulmonary-renal syndromes (hemoptysis + renal disease).",
  "a":"1. Goodpasture syndrome, 2. Henoch-Schönlein purpura, 3. SLE, 4. Microscopic polyangiitis, 5. Cryoglobulinemia, 6. Advanced uremia with pulmonary edema/coagulopathy, 7. TTP, 8. Pulmonary embolism with RV thrombosis."},
 {"cat":"Anti-GBM","q":"Describe the treatment protocol of anti-GBM disease.",
  "a":"<b>3 days pulse methylprednisolone</b> (7–15 mg/kg/day, max 1 g/day) → <b>2 weeks daily plasmapheresis</b> (40–50 ml/kg plasma with albumin replacement, until antibody disappears) → <b>6 months oral corticosteroids</b> (1 mg/kg/day → 20 mg/day by 6 wk) + <b>3 months cyclophosphamide</b>."},
 {"cat":"Anti-GBM","q":"When should plasmapheresis NOT be given in anti-GBM disease?",
  "a":"In patients with <b>anuria and/or crescents &gt;85%</b> of glomeruli — <b>unless there is pulmonary hemorrhage</b>. Albumin is the recommended replacement fluid (fewer complications)."},
 {"cat":"PSGN","q":"Which organism causes post-streptococcal GN and what are the latent periods?",
  "a":"Group A <b>β-hemolytic streptococci</b>, nephritogenic strains <b>1, 4, 12, 49</b> (type 49 most commonly isolated). Latent period: <b>1–2 weeks</b> after throat infection; <b>~4 weeks</b> after skin infection."},
 {"cat":"PSGN","q":"What % of infected individuals develop GN, and what is the presentation spectrum?",
  "a":"~<b>10%</b> develop GN; infection may be mild/unnoticed, and there is <b>no relationship between severity of infection and risk of GN</b>. Presentations: acute GN (children), insidious/subacute in adults; nephrotic syndrome &lt;20%; RPGN in ~5%; asymptomatic (found on routine urine)."},
 {"cat":"PSGN","q":"What is the biopsy triad of PSGN?",
  "a": "<b>EM:</b> subepithelial electron-dense deposits (<span class='hl'>humps</span>) + <b>IF:</b> granular deposits of <b>C3 &amp; IgG</b> + <b>serum:</b> transient low C3 recovering within <b>8 weeks</b>."},
 {"cat":"PSGN","q":"What is the role of penicillin in PSGN — for patients and close contacts?",
  "a": "Patients: penicillin reduces antigen load and spread to contacts but does NOT reliably abort/ameliorate the course. Close contacts: short-term prophylaxis (<b>phenoxy penicillin 500 mg/day</b>) for high-risk individuals in closed communities. No benefit of long-term penicillin after GN develops; defer tonsillectomy until convalescence."},
 {"cat":"Lupus","q":"Give the prevalence and hallmark renal histology of lupus nephritis.",
  "a": "Kidney is the <b>most common organ involved</b> in SLE; ~<b>50%</b> of lupus patients have LN at diagnosis. Pathology: <b>hematoxylin bodies</b> (pathognomonic, ~2%), <b>wire-loop deposits</b> (subendothelial, best on trichrome/silver), <b>hyaline thrombi</b> (intraluminal deposits). Tubulo-interstitial disease in ~50%."},
 {"cat":"Lupus","q":"Summarize the ISN/RPS classes of lupus nephritis.",
  "a": "<ul><li><b>I:</b> Minimal mesangial (normal LM, mesangial deposits on IF/EM)</li><li><b>II:</b> Mesangial proliferative</li><li><b>III:</b> Focal proliferative — <b>&lt;50%</b> glomeruli</li><li><b>IV:</b> Diffuse proliferative — <b>&gt;50%</b> glomeruli</li><li><b>V:</b> Membranous</li><li><b>VI:</b> Advanced — global sclerosis of <b>≥90%</b> glomeruli</li></ul>"},
 {"cat":"Lupus","q":"What does the renal biopsy add in lupus nephritis?",
  "a": "Determines the pathological class; excludes other lesions (hypersensitivity interstitial nephritis, pure antiphospholipid syndrome); and gives the <b>activity index (0–24)</b> and <b>chronicity index (0–12)</b> that guide therapy and prognosis."},
 {"cat":"Lupus","q":"Outline management and prognosis of lupus nephritis.",
  "a": "Management: <b>hydroxychloroquine for all</b> (unless contraindicated); BP target <b>≤120/80</b>; ACEIs/ARBs + protein restriction; statins; avoid nephrotoxic drugs (NSAIDs) &amp; pregnancy in active LN; corticosteroids + immunosuppression (cyclophosphamide, MMF, azathioprine, cyclosporine) in <b>induction → maintenance</b> phases. Prognosis: classes <b>I, II, V good</b>; <b>III, IV poor</b> (→ESRD, especially IV); VI → dialysis/transplant."},
 {"cat":"Diabetic","q":"List the renal complications of diabetes mellitus.",
  "a": "1. <b>Diabetic nephropathy (diabetic glomerulosclerosis)</b>, 2. Papillary necrosis, 3. UTI (asymptomatic bacteriuria, pyelonephritis, perinephric abscess), 4. Ischemic nephropathy (renal artery atherosclerosis), 5. Hydronephrosis (atonic bladder), 6. AKI (contrast nephropathy, obstruction from papillary necrosis)."},
 {"cat":"Diabetic","q":"Describe the 5 stages of diabetic nephropathy.",
  "a": "<ul><li><b>I — Hyperfiltration:</b> GFR ↑20–40%, kidney hypertrophy</li><li><b>II — Silent:</b> normal GFR, normal albumin (&lt;30 mg/day)</li><li><b>III — Incipient:</b> GFR starts declining; <b>microalbuminuria 30–300 mg/day</b> (5–10 y after onset)</li><li><b>IV — Overt:</b> proteinuria &gt;0.5 gm/day, ↓GFR, HTN</li><li><b>V — ESRD:</b> needs RRT; other diabetic complications present</li></ul>"},
 {"cat":"Diabetic","q":"What are the 3 major renal lesions of diabetic nephropathy?",
  "a": "<ul><li><b>Glomerulosclerosis</b> — diffuse (common, non-specific) and/or <b>nodular</b> (less common but <span class='hl'>pathognomonic</span>)</li><li>Chronic tubulo-interstitial nephritis</li><li>Vasculitic lesions — arteriolosclerosis of <b>afferent AND efferent</b> arterioles (pathognomonic for DM)</li></ul>"},
 {"cat":"Diabetic","q":"List risk factors for progression of diabetic nephropathy.",
  "a": "Proteinuria, hypertension, hyperglycemia, <b>smoking</b>, high-protein diet, and genetic factors."},
 {"cat":"Diabetic","q":"When is renal biopsy needed to diagnose DN as the cause of CKD?",
  "a": "When: DM duration &lt;10 y without retinopathy/neuropathy; suspicion of alternative diagnosis (sudden NS early in DM, active urinary sediment with renal insufficiency), or when criteria of typical DN are absent."},
 {"cat":"Diabetic","q":"What are the BP goals and drug choices in diabetic nephropathy?",
  "a": "Goals: <b>&lt;130/80</b> without proteinuria; <b>&lt;125/75</b> with proteinuria. Drugs: ACEI/ARBs first-line, + diuretics, non-dihydropyridine CCBs (verapamil, diltiazem), β-blockers, alpha-blockers (prazosin). <b>Reduce insulin dose</b> in DN (kidney clears insulin → prolonged half-life → hypoglycemia risk)."},
]

# ============================================================
# GROUP 02 — Acute Kidney Injury
# ============================================================
aki = [
 {"cat":"Definition","q":"Define AKI.",
  "a":"An <b>abrupt (within 48 hours)</b> and <b>sustained decrease in kidney function</b>, with a rise in serum creatinine, fall in urine output, or both — a term covering the whole spectrum from mild transient creatinine rise to overt renal failure needing RRT."},
 {"cat":"Staging","q":"Summarize the RIFLE / AKIN staging of AKI.",
  "a": "<ul><li><b>Risk/1:</b> Cr ×1.5–2 or ↑≥0.3; UOP &lt;0.5 ml/kg/h ×6 h</li><li><b>Injury/2:</b> Cr ×2; UOP &lt;0.5 ml/kg/h ×12 h</li><li><b>Failure/3:</b> Cr ×3 or ≥4.0 (+0.5 rise); UOP &lt;0.3 ml/kg/h ×24 h or anuria 12 h</li><li><b>Loss:</b> persistent loss &gt;4 weeks</li><li><b>ESRD:</b> permanent loss &gt;3 months</li></ul>"},
 {"cat":"Causes","q":"List the 4 categories of pre-renal AKI with examples.",
  "a": "<ul><li><b>↓ effective ECF volume:</b> hemorrhage, vomiting, diarrhea, burns, diuretics; redistribution (liver failure, NS, pancreatitis)</li><li><b>↓ cardiac output:</b> cardiogenic shock, MI, arrhythmias, CHF, tamponade</li><li><b>Peripheral vasodilation:</b> sepsis, hypotension, anaphylaxis</li><li><b>Renal vasoconstriction:</b> PG inhibition (NSAIDs), adrenergics, hepato-renal syndrome, hypercalcemia</li><li><b>Efferent vasodilation:</b> ACEIs/ARBs → ↓ intraglomerular pressure</li></ul>"},
 {"cat":"Causes","q":"List the intrinsic (intra-renal) causes of AKI.",
  "a": "<ul><li><b>ATN:</b> hemodynamic (sepsis, surgery), toxic (aminoglycosides, contrast, heavy metals), intratubular deposits (urate, myeloma, oxalate, sulfadiazine), pigments (myoglobin, hemoglobin)</li><li><b>Acute GN</b> (e.g., RPGN)</li><li><b>Acute interstitial nephritis</b> (drug/infection)</li><li><b>Renal vascular occlusion:</b> arterial/venous thrombosis, vasculitis, cortical necrosis</li></ul>"},
 {"cat":"Causes","q":"List post-renal (obstructive) causes of AKI.",
  "a": "Congenital anomalies (ureterocele, PUV, neurogenic bladder); acquired uropathies (BPH, ureterolithiasis, papillary necrosis, ureteral ligation); malignancy (prostate, bladder, cervix, colon); gynecologic (prolapse, endometriosis); drugs (sulfonamides); infections (schistosomiasis, TB); catheter occlusion."},
 {"cat":"Clinical","q":"Define oliguria in AKI and why is it important?",
  "a": "Oliguria = &lt;300 ml/day (&lt;5 ml/kg/day or 0.5 ml/kg/h). <b>Oliguria alone is the best predictor of AKI</b> — but ≥50% of AKI cases are non-oliguric, so normal urine output does not exclude AKI."},
 {"cat":"Clinical","q":"List causes of anuric AKI.",
  "a": "<ul><li><b>Complete urinary tract obstruction — ~90% of cases</b></li><li>Renal artery/vein thrombosis</li><li>Cortical necrosis (sepsis, obstetric accidents, DIC)</li><li>Renal vasculitis &amp; RPGN</li><li>AKI complicating sepsis, heat stroke, rhabdomyolysis</li></ul>"},
 {"cat":"Investigations","q":"What do muddy brown casts, RBC casts, WBC casts, and urine eosinophils suggest in AKI?",
  "a": "<b>Muddy brown casts</b> (+ tubular cell casts, oxalate crystals) → ATN. <b>Dysmorphic RBCs / RBC casts</b> → GN. <b>WBC casts / WBCs + eosinophils</b> → pyelonephritis or acute interstitial nephritis (AIN)."},
 {"cat":"Investigations","q":"Reddish-brown (cola) urine with a positive dipstick for blood but NO red cells on microscopy — what is it?",
  "a": "Suggests <b>myoglobin (rhabdomyolysis) or hemoglobin (hemolysis)</b> — pigment nephropathy."},
 {"cat":"Investigations","q":"Write the FENa formula and its interpretation.",
  "a": "FENa = (UNa/PNa) ÷ (UCr/PCr) × 100. <b>&lt;1% → pre-renal AKI; &gt;1% → ATN.</b> Exceptions (ATN with FENa &gt;1% but paradoxically low): radio-contrast, severe burns, acute GN, rhabdomyolysis. Only valid in oliguric AKI — not in diuretic use, GN, cirrhosis, or non-oliguric states."},
 {"cat":"Investigations","q":"When is FEurea used and how is it interpreted?",
  "a": "Used in patients <b>receiving diuretics</b> (urea transport is not affected by diuretics). <b>&lt;35% → pre-renal</b>."},
 {"cat":"Investigations","q":"What does the BUN/creatinine ratio indicate in AKI?",
  "a": "<b>≥20:1 → pre-renal AKI.</b> &lt;20:1 → intrinsic or post-renal AKI."},
 {"cat":"Investigations","q":"Match biomarkers to causes: ↑uric acid, ↑LDH, schistocytes, rouleaux, myoglobin.",
  "a": "<ul><li>↑Uric acid → <b>tumor lysis syndrome</b></li><li>↑LDH → <b>renal infarction</b></li><li>Schistocytes → <b>HUS/TTP</b></li><li>Rouleaux → <b>multiple myeloma</b></li><li>Myoglobin/free Hb → pigment nephropathy</li></ul>"},
 {"cat":"Investigations","q":"What are the bladder-pressure thresholds relevant to AKI?",
  "a": "<b>&lt;10 mmHg</b> = normal; <b>&gt;10 mmHg</b> = abnormal; <b>15–25 mmHg</b> = risk of abdominal compartment syndrome and AKI."},
 {"cat":"Investigations","q":"When is renal biopsy indicated in AKI?",
  "a": "When the cause of <b>intrinsic</b> renal AKI is <b>unclear</b> after excluding pre- and post-renal causes — it distinguishes ATN from AIN, GN, and vascular causes."},
 {"cat":"Treatment","q":"What are the principles of AKI treatment?",
  "a": "No definitive therapy exists — <b>supportive care is the mainstay</b>: (A) recognize &amp; manage etiology and risk factors (DM, CKD, HTN, cardiac/liver dysfunction); (B) monitor creatinine &amp; urine output for staging; (C) manage comorbidities — tight glucose control, hyperkalemia, avoid nephrotoxins, maintain renal perfusion (volume, inotropes); (D) RRT for uremia, refractory hyperkalemia/acidosis/hypervolemia; many start dialysis empirically at BUN &gt;100 mg/dl."},
 {"cat":"CIN","q":"Define contrast-induced nephropathy (CIN) and list risk factors.",
  "a": "Rise of serum creatinine <b>≥0.5 mg/dl or ≥25% above baseline within 48 h</b> after contrast. Patient factors: <b>pre-existing CKD (most potent; ~60% of cases)</b>, DM, CHF, hypotension, volume depletion, old age. Contrast factors: large volume, <b>high-osmolar</b> contrast."},
 {"cat":"CIN","q":"Describe the pathogenesis of CIN.",
  "a": "1. <b>Renal ischemia</b> — vasoconstrictive compounds (endothelin, adenosine) + ↑ tubular oxygen utilization. 2. <b>Hyperosmolarity</b> — ↑ intratubular pressure ↓ GFR, ↑ tubular apoptosis. 3. <b>Oxygen free radicals</b> → oxidative injury. 4. <b>Direct cellular toxicity</b>."},
 {"cat":"CIN","q":"What is the creatinine course in CIN?",
  "a": "Rises 24–48 h after exposure, <b>peaks in 3–5 days</b>, returns to baseline in <b>7–10 days</b>. Severe cases peak at 5–10 days with oliguria and possible dialysis."},
 {"cat":"CIN","q":"How is CIN prevented?",
  "a": "Use <b>low-osmolar, non-iodinated</b> contrast; minimize volume (5 ml/kg, max 300 ml, ÷ serum creatinine); space out administrations; avoid nephrotoxins; <b>adequate hydration</b> before/during/after; N-acetylcysteine is of unclear benefit. No specific therapy once CIN occurs."},
 {"cat":"TLS","q":"Define tumor lysis syndrome (TLS) and who is at risk?",
  "a": "Acute critical illness from massive sudden tumor-cell death after chemotherapy — <b>hyperuricemia, hyperphosphatemia, hyperkalemia, hypocalcemia (secondary to hyperphosphatemia), AKI</b>. At risk: rapidly growing cancers (especially <b>Burkitt's lymphoma</b>), ↑LDH, volume depletion, acidic urine, CKD."},
 {"cat":"TLS","q":"How is TLS prevented before chemotherapy?",
  "a": "Identify at-risk patients; correct fluids/electrolytes; maintain hydration &amp; urine output; <b>alkalinize urine to pH &gt;7.0</b>; oral phosphate-binding antacids; <b>allopurinol 300 mg/m² 1–2 days before</b> chemotherapy. (Urine alkalinization + allopurinol = cornerstones.)"},
 {"cat":"TLS","q":"How is established AKI in TLS treated?",
  "a": "Allopurinol 600 mg/day; IV isotonic NaHCO₃ 200–300 ml/h (expand volume + alkalinize); <b>hemodialysis is life-saving</b> — lowers uric acid, phosphorus, potassium; corrects volume overload &amp; uremia. Stop alkalinization once uric acid normal (avoid Ca₃(PO₄)₂ precipitation); treat symptomatic hypocalcemia only after correcting hyperphosphatemia."},
 {"cat":"Rhabdo","q":"Define rhabdomyolysis and list its main causes.",
  "a": "Injury/metabolic defect of skeletal muscle → cell-membrane lysis with leakage of myoglobin, enzymes, phosphorus, potassium. Causes: direct trauma (crush, electric shock, burns); excessive exercise/seizures; hereditary myopathies (McArdle's); acquired metabolic (hyperthyroidism, hypokalemia, DKA, alcoholism); hypoxia/ischemia (CO poisoning, compartment syndrome); drugs (statins, cocaine); infections (Coxsackie, HIV, Legionella); toxins (snake venom, Haff disease); malignant hyperthermia, NMS."},
 {"cat":"Rhabdo","q":"Explain the mechanism of AKI in severe rhabdomyolysis.",
  "a": "<b>1. Renal ischemia</b> — myoglobin is a potent renal vasoconstrictor. <b>2. Tubular obstruction/injury</b> — filtered myoglobin enters PCT cells where iron compounds are toxic; unabsorbed pigment reaches the distal nephron and with <b>Tamm-Horsfall protein in acidic urine</b> forms a gel that obstructs urine flow."},
 {"cat":"Rhabdo","q":"How is rhabdomyolysis diagnosed?",
  "a": "Clinical: muscle pain, tenderness, weakness (severe: crush injury + AKI). Lab: serum <b>CK &gt;500 IU/L</b> raises suspicion; the <b>CK-MM isoform is the most sensitive test</b> to confirm."},
 {"cat":"Rhabdo","q":"How is rhabdomyolysis treated?",
  "a": "ICU care for severe cases; <b>aggressive/urgent volume replacement</b> (avoid overload); <b>urine alkalinization</b> with bicarbonate to prevent cast obstruction; watch respiratory failure (diaphragmatic weakness); monitor hyperkalemia (ECG + K); dialysis for severe AKI."},
]

# ============================================================
# GROUP 03 — Chronic Kidney Disease & RRT
# ============================================================
ckd = [
 {"cat":"Definitions","q":"Define CKD, CRF and ESRD.",
  "a": "<ul><li><b>CKD:</b> abnormalities of kidney structure or function present <b>&gt;3 months</b> with health implications; classified by cause + GFR category + albuminuria category</li><li><b>CRF:</b> GFR &lt;60 ml/min/1.73 m² for ≥3 months (Grade 3 CKD)</li><li><b>ESRD:</b> permanent irreversible renal impairment requiring RRT = Grade 5 CKD</li></ul>"},
 {"cat":"Definitions","q":"List markers of kidney damage (functional and structural).",
  "a": "<b>Functional:</b> albuminuria (AER ≥30 mg/24 h or ACR ≥30 mg/g), urine sediment abnormalities, electrolyte/tubular abnormalities. <b>Structural:</b> histologic abnormalities, imaging abnormalities, history of kidney transplantation."},
 {"cat":"Definitions","q":"Give the GFR grades (stages) of CKD.",
  "a": "<ul><li><b>G1:</b> ≥90 (normal/high)</li><li><b>G2:</b> 60–89 (mildly decreased)</li><li><b>G3a:</b> 45–59</li><li><b>G3b:</b> 30–44</li><li><b>G4:</b> 15–29 (severely decreased)</li><li><b>G5:</b> &lt;15 (ESRD)</li></ul>Without kidney damage, G1/G2 do not fulfill CKD criteria."},
 {"cat":"Definitions","q":"Give the albuminuria categories A1–A3.",
  "a": "<ul><li><b>A1:</b> AER &lt;30 mg/24 h (ACR &lt;30 mg/g) — normal to mildly increased</li><li><b>A2:</b> 30–300 — moderately increased</li><li><b>A3:</b> &gt;300 — severely increased (nephrotic usually &gt;2200)</li></ul>"},
 {"cat":"Clinical","q":"List the GIT manifestations of CKD.",
  "a": "Anorexia, nausea, vomiting &amp; hiccough (early, respond to protein restriction); <b>uremic fetor</b> (urea → ammonia breath); mucosal ulcerations → GIT bleeding; peptic ulcer (↑gastrin, ↑acidity, secondary hyperparathyroidism); increased diverticulosis in PCKD. GIT symptoms improve with dialysis — except peptic ulcer &amp; diverticulosis."},
 {"cat":"Clinical","q":"Why is anemia so common in CKD?",
  "a": "<b>Erythropoietin deficiency</b> (main cause); ↓ RBC lifespan + toxic marrow suppression; ↓ nutrient intake/absorption (iron, B12, folate); bleeding tendency; secondary hyperparathyroidism; chronic inflammation; dialysis blood loss &amp; GIT losses."},
 {"cat":"Clinical","q":"List endocrine abnormalities in CKD.",
  "a": "Insulin resistance + impaired glucose tolerance; <b>↓ insulin requirement</b> in diabetics (decreased renal degradation); thyroid dysfunction; ↑TRH → hyperprolactinemia → galactorrhea/amenorrhea/impotence; hypocalcemia → secondary hyperparathyroidism; ↓ testosterone → impotence, ↓spermatogenesis; menstrual abnormalities &amp; infertility."},
 {"cat":"Bone","q":"Define CKD-MBD and its 3 components.",
  "a": "A systemic disorder of mineral &amp; bone metabolism in CKD: <ul><li>1. Abnormalities of calcium, phosphorus, PTH or vitamin D metabolism</li><li>2. Renal osteodystrophy (bone abnormalities)</li><li>3. Vascular/soft-tissue calcification (e.g., calciphylaxis)</li></ul>"},
 {"cat":"Bone","q":"Explain the pathophysiology of secondary hyperparathyroidism in CKD.",
  "a": "↓GFR (&lt;60) → <b>↓ phosphorus filtration → hyperphosphatemia</b> → PTH stimulation. ↓ renal 1α-hydroxylase → <b>↓ active vitamin D (1,25(OH)₂D) → hypocalcemia</b>. Both hyperphosphatemia and hypocalcemia drive secondary hyperparathyroidism."},
 {"cat":"Bone","q":"List the 5 types of renal osteodystrophy.",
  "a": "<ul><li>1. <b>Osteitis fibrosa</b> (high-turnover; hyperparathyroidism; peritrabecular fibrosis)</li><li>2. <b>Osteomalacia</b> (low bone turnover)</li><li>3. <b>Adynamic bone disease</b> (↓ formation, normal mineralization; aggressive PTH suppression)</li><li>4. <b>Osteopenia/osteoporosis</b> (↓ bone quantity/quality)</li><li>5. <b>Mixed lesions</b></li></ul>"},
 {"cat":"Clinical","q":"What is dialysis disequilibrium syndrome?",
  "a": "Nausea, vomiting, drowsiness, headache, seizures in the first few dialysis sessions — rapid urea removal lowers ECF osmolality faster than brain osmolality → cerebral edema &amp; ↑ICP."},
 {"cat":"Clinical","q":"List important dermatological signs of CKD.",
  "a": "Earthy (muddy) face (anemia + urochrome); pallor; ecchymoses/hematomas; <b>pruritus</b> (Ca deposition + SHPT — persists after dialysis); <b>uremic frost</b> (advanced; urea in sweat); slate-gray-bronze discoloration (hemochromatosis from transfusions); half-and-half nails; <b>calciphylaxis</b> (calcific uremic arteriolopathy — violaceous rash, nonhealing ulcers, gangrene, high mortality)."},
 {"cat":"Clinical","q":"Why is tetany rare in CKD despite hypocalcemia?",
  "a": "Because <b>metabolic acidosis increases ionized calcium</b>."},
 {"cat":"Investigations","q":"Which findings suggest chronicity (CKD) rather than AKI when a patient presents with renal failure?",
  "a": "Bone disease; uremic neuropathy; <b>profound anemia</b>, hyperphosphatemia, high creatinine with mild symptoms; <b>small kidneys on imaging</b> — except in DM, amyloidosis, multiple myeloma and PCKD (kidneys may be normal/large)."},
 {"cat":"Investigations","q":"When is renal biopsy NOT indicated in CKD work-up?",
  "a": "If there is a <b>small atrophic kidney</b>."},
 {"cat":"Treatment","q":"List the reversible factors to correct in CKD to delay progression.",
  "a": "Good glucose control; good BP control; hydration; correction of obstruction &amp; UTI; treat active primary renal disease; treat sepsis; reduce proteinuria (ACEI/ARB, <b>avoid combination</b>); control dyslipidemia; lifestyle modification; avoid nephrotoxins &amp; large contrast doses."},
 {"cat":"Treatment","q":"What dietary advice is given in CKD?",
  "a": "Low-protein diet <b>0.6–0.8 gm/kg/day</b> (increase once dialysis starts); low potassium (↑ if hypokalemic); low phosphate; salt restriction (free salt in salt-losing nephropathy); fluid balance according to urine output."},
 {"cat":"Treatment","q":"Which phosphate binders are used, and when are calcium-based ones avoided?",
  "a": "<b>Calcium-based</b> (Ca carbonate with meals): effective first-line but long-term hypercalcemia; <b>avoid in dialysis patients with hypercalcemia and when PTH &lt;130 pg/dL</b> — then use <b>calcium-free</b> (sevelamer, lanthanum carbonate)."},
 {"cat":"Treatment","q":"When is parathyroidectomy indicated in CKD?",
  "a": "Severe hyperparathyroidism with <b>PTH &gt;800 pg/dL</b> not responding to medical therapy. Other tools: calcimimetics (cinacalcet), vitamin D analogs (alfacalcidol/calcitriol 0.25–2 µg daily, held in hypercalcemia/hyperphosphatemia)."},
 {"cat":"Treatment","q":"How is renal anemia treated?",
  "a": "Iron therapy (oral pre-dialysis; IV better for HD); erythropoietin (alpha/beta, long-acting <b>darbepoetin alfa</b>, CERA) subcutaneous or IV."},
 {"cat":"RRT","q":"List the temporary (acute/urgent) indications of dialysis.",
  "a": "In AKI (early dialysis simplifies management); uremic complications: <b>refractory hyperkalemia, intractable acidosis, fluid overload unresponsive to diuretics, pericarditis/pleuritis, CNS &amp; GIT complications, uremic bleeding</b>; and removal of dialyzable toxins/drugs (alcohols, aspirin, lithium, contrast)."},
 {"cat":"RRT","q":"What is the indication for permanent (maintenance) dialysis?",
  "a": "Grade 5 CKD (ESRD) when <b>GFR ≤10 ml/min</b> (may correspond to serum creatinine 8–10 mg/dL)."},
 {"cat":"RRT","q":"List contraindications to dialysis.",
  "a": "Refractory hypotension unresponsive to vasopressors; terminal illness; organic brain damage."},
 {"cat":"RRT","q":"What are the principles and specific indications of peritoneal dialysis?",
  "a": "Uses the <b>peritoneal membrane</b> as the semipermeable membrane; fluid instilled equilibrates with ECF and effluent removes solutes/water. Indications: slowly rising urea; cardiovascular/hemodynamic instability; no HD facilities; immature A-V fistula; poor vascular access; high anticoagulation risk."},
 {"cat":"RRT","q":"What are the absolute contraindications of peritoneal dialysis?",
  "a": "<ul><li><b>Peritoneal fibrosis (&gt;50%)</b> — inadequate surface area</li><li><b>Pleuro-peritoneal leak</b> → hydrothorax</li><li>Multiple large abdominal wounds with drains</li></ul>"},
 {"cat":"RRT","q":"List the advantages of peritoneal dialysis over HD.",
  "a": "Safe &amp; easy; <b>preserves residual renal function</b>; no routine anticoagulation; no vascular surgery; slow clearance → fewer disequilibrium/hypotension symptoms; better PTH control; more liberal diet; fewer medications; cheaper; less blood-borne virus transmission."},
 {"cat":"RRT","q":"List major complications of peritoneal dialysis.",
  "a": "<b>Peritonitis</b>; catheter exit-site infection; constipation; dialysate leakage (pleural effusion/scrotum); ultrafiltration failure; sclerosing peritonitis (rare, fatal); protein loss → malnutrition; hyperlipidemia; obesity (glucose absorption); hernias; traumatic perforation; cannula clotting."},
 {"cat":"RRT","q":"List the surgical (vascular access) complications of hemodialysis.",
  "a": "Catheters: bleeding, infection, thrombosis/stenosis, pneumothorax, air embolism. A-V fistula/graft: stenosis, thrombosis, infection, poor venous outflow, <b>vascular steal → limb ischemia</b>, venous hypertension syndrome, high-output heart failure, pseudo-aneurysms."},
 {"cat":"RRT","q":"List the acute medical complications of hemodialysis.",
  "a": "Intradialytic hypotension; hypertension; cramps; nausea/vomiting; headache; fever; hemolysis (rare); bleeding (anticoagulant overdose); circuit clotting; chest pain; arrhythmias; cardiac arrest; air embolism; disequilibrium syndrome."},
 {"cat":"RRT","q":"List chronic (long-term) HD complications — cardiovascular and others.",
  "a": "<b>Cardiovascular:</b> ischemic/valvular heart disease, uremic pericarditis/endocarditis, dilated cardiomyopathy, peripheral vascular disease, metastatic calcification. <b>Others:</b> neuropsychiatric (anxiety, depression, dementia), malnutrition, dialysis osteomalacia, <b>dialysis-related amyloidosis (DRA)</b>, crystal arthropathy, bone/joint infection, ischemic bone necrosis, hypersplenism, acquired renal cystic disease (&gt;3 years of dialysis, may turn malignant)."},
 {"cat":"Transplant","q":"List the contraindications to kidney transplantation.",
  "a": "Patient refusal; psychosis; active sepsis; unstable cardiovascular disease; severe respiratory distress; cerebrovascular hemorrhage; advanced liver disease (unless combined liver-kidney); malignancy; unrepairable urological abnormalities; elderly (relative)."},
 {"cat":"Transplant","q":"List the medical complications of transplantation.",
  "a": "ATN; <b>rejection (hyperacute, acute, chronic)</b>; complications of immunosuppression; recurrence of primary disease; opportunistic infection; malignancy (Kaposi sarcoma, lymphoproliferative); hypertension, DM, atherosclerosis, bone disease; GIT bleeding, cataract, marrow suppression; nephro-/hepatotoxicity."},
]

# ============================================================
# GROUP 04 — Electrolytes & Acid-Base
# ============================================================
electrolytes = [
 {"cat":"Acid-Base","q":"Give the primary event and direction of change in the 4 acid-base disturbances.",
  "a": "<ul><li><b>Metabolic acidosis:</b> primary ↓HCO₃⁻ → pH↓, compensatory CO₂↓ (hyperventilation)</li><li><b>Metabolic alkalosis:</b> primary ↑HCO₃⁻ → pH↑, CO₂↑</li><li><b>Respiratory acidosis:</b> primary CO₂ retention → pH↓, kidneys retain HCO₃⁻ (HCO₃↑)</li><li><b>Respiratory alkalosis:</b> primary CO₂ loss → pH↑, kidneys excrete HCO₃⁻ (HCO₃↓)</li></ul>"},
 {"cat":"Acid-Base","q":"Write the anion gap formula and what it represents.",
  "a": "AG = Na⁺ − (HCO₃⁻ + Cl⁻). Plasma is electro-neutral; unmeasured anions (sulfate, phosphate, organic anions) slightly exceed unmeasured cations — that difference is the anion gap. ↑AG occurs with ↓ unmeasured cations (e.g., hypokalemia) or ↑ unmeasured anions (e.g., hyperphosphatemia)."},
 {"cat":"Acid-Base","q":"List causes of high-anion-gap metabolic acidosis.",
  "a": "Ketoacidosis; renal failure (uremia); lactic acidosis; massive rhabdomyolysis; exogenous toxins (salicylate, methanol, ethylene glycol, metformin). Mnemonic <b>K.U.S.M.A.U.L.</b> — Ketoacidosis, Uremia, Salicylates, Methanol, Alcohol, Uric acid (rhabdomyolysis), Lactic acidosis."},
 {"cat":"Acid-Base","q":"List causes of normal-anion-gap (hyperchloremic) metabolic acidosis.",
  "a": "GI loss of HCO₃⁻ (diarrhea, enteric fistula); renal HCO₃⁻ loss (<b>proximal type II RTA</b>); failure of H⁺ secretion (<b>distal type I RTA</b>); acid infusion (ammonium chloride, hyperalimentation)."},
 {"cat":"Acid-Base","q":"What is the hallmark respiratory sign of metabolic acidosis?",
  "a": "<b>Kussmaul respiration</b> — rapid, deep sighing breathing as the body blows off CO₂ to compensate."},
 {"cat":"Acid-Base","q":"When is alkali therapy indicated in metabolic acidosis and what is the deficit formula?",
  "a": "To raise pH above <b>7.20</b> when HCO₃⁻ low + PCO₂ near the compensation limit (~15 mmHg), or when well-compensated acidosis threatens respiratory failure. IV NaHCO₃ deficit = (Desired HCO₃⁻ − Measured HCO₃⁻) × 0.5 × body weight (kg). Oral HCO₃⁻ for chronic acidosis (e.g., RTA)."},
 {"cat":"Acid-Base","q":"How is metabolic alkalosis classified (first step)?",
  "a": "By <b>urine chloride</b>: <b>Chloride-responsive</b> (&lt;20 mEq/L), <b>Chloride-resistant</b> (&gt;20 mEq/L), and other causes (alkali loading)."},
 {"cat":"Acid-Base","q":"List causes of chloride-responsive metabolic alkalosis.",
  "a": "Loss of gastric secretions (vomiting, NG suction); loss of colonic secretions (chloridorrhea, villous adenoma); volume depletion; thiazide/loop diuretics (after discontinuation); cystic fibrosis."},
 {"cat":"Acid-Base","q":"List causes of chloride-resistant metabolic alkalosis — with and without hypertension.",
  "a": "<b>With hypertension:</b> hyperaldosteronism (Conn, GRA), Cushing syndrome, exogenous steroids, Liddle syndrome, renovascular hypertension. <b>Without hypertension:</b> Bartter syndrome, Gitelman syndrome, severe K⁺ depletion, current thiazide/loop diuretic use, hypomagnesemia."},
 {"cat":"Acid-Base","q":"What signs point to hypocalcemia in metabolic alkalosis?",
  "a": "Tetany, <b>Chvostek sign, Trousseau sign</b>, perioral tingling, muscle cramps, carpopedal spasms (decreased ionized calcium)."},
 {"cat":"Acid-Base","q":"How is chloride-responsive metabolic alkalosis treated?",
  "a": "Volume-depleted: <b>isotonic 0.9% NaCl</b> + potassium chloride. Volume-overloaded (edematous): potassium chloride ± carbonic anhydrase inhibitors or K⁺-sparing diuretics. Chloride-resistant: treat the specific cause (hyperaldosteronism, stop diuretics, replace Mg²⁺/K⁺)."},
 {"cat":"Hyponatremia","q":"Define hyponatremia and pseudohyponatremia.",
  "a": "Hyponatremia: serum Na <b>&lt;135 mmol/L</b>. Most common form is <b>dilutional</b> (water retention). <b>Pseudohyponatremia:</b> spuriously low measured Na with normal true plasma Na — when serum lipids/proteins are markedly elevated; plasma osmolality stays normal (vs low in true hypotonic hyponatremia)."},
 {"cat":"Hyponatremia","q":"What are the pathological effects and neurological manifestations of hyponatremia?",
  "a": "Water shifts ECF → ICF → <b>cell swelling → brain edema</b>. Manifestations: altered personality, lethargy, confusion → stupor, neuromuscular hyperexcitability, hyperreflexia, <b>seizures, coma, death</b>. Severity correlates with severity and <b>rate of development</b>."},
 {"cat":"Hyponatremia","q":"Classify hyponatremia by osmolality and volume status.",
  "a": "By osmolality: <b>Hypertonic &amp; isotonic = pseudohyponatremia</b>; <b>hypotonic = true hyponatremia</b>, then subclassified by volume: <b>hypervolemic</b> (HF, cirrhosis, nephrotic, CKD), <b>euvolemic</b> (SIADH — prototype, primary polydipsia, hypothyroidism, thiazides), <b>hypovolemic</b> (extra-renal loss — vomiting/diarrhea; renal loss — diuretics, adrenal insufficiency, salt-losing nephritis, recovery phase of AKI)."},
 {"cat":"Hyponatremia","q":"What is the risk of over-rapid correction of chronic hyponatremia?",
  "a": "<b>Osmotic demyelination syndrome (central pontine myelinolysis)</b> — correct slowly in chronic cases. Fluid of choice by volume status: isotonic 0.9% NaCl (hypo/euvolemic), hypertonic 3% NaCl + loop diuretics (hyper/euvolemic); vasopressin antagonists (conivaptan, tolvaptan) for SIADH."},
 {"cat":"Hypernatremia","q":"Define hypernatremia and explain why it almost always means water deficit.",
  "a": "Serum Na <b>&gt;145 mmol/L</b>. Sodium is an osmotically effective ECF solute, so hypernatremia always reflects <b>hypertonicity</b> from a water deficit (TBW deficit &gt; Na deficit). Normally ADH and thirst defend against it — it occurs when these defenses fail."},
 {"cat":"Hypernatremia","q":"What are the pathological effects of hypernatremia on the brain?",
  "a": "Water shifts ICF → ECF → <b>cell shrinkage</b> → neurological sequelae and <b>intracerebral hemorrhage</b> (punctate or major vessel disruption)."},
 {"cat":"Hypernatremia","q":"Classify hypernatremia by volume status with examples.",
  "a": "<ul><li><b>Hypervolemic:</b> excessive sodium administration (hypertonic 3% saline, NaHCO₃)</li><li><b>Euvolemic:</b> pure water loss — renal (diabetes insipidus, low urine osmolality) vs extra-renal (rhabdomyolysis, high urine osmolality)</li><li><b>Hypovolemic:</b> hypotonic fluid loss — renal Na loss (diuretics, polyuric ATN) vs extra-renal (GIT/respiratory/skin)</li></ul>"},
 {"cat":"Hypernatremia","q":"How is hypernatremia treated?",
  "a": "First resuscitation of volume with <b>isotonic 0.9% NaCl</b>; then gradual maintenance correction: TBW deficit = 0.6 × premorbid weight × (1 − 140/Na) + daily requirements, using oral water, IV 5% glucose or 0.45% NaCl. <b>Correct gradually — 0.5–1 mmol/L/hour — to avoid brain edema</b>."},
 {"cat":"Hyperkalemia","q":"Define hyperkalemia and list causes of increased K⁺ release from cells.",
  "a": "Serum K <b>&gt;5.5 mmol/L</b>. Increased release: <b>pseudo-hyperkalemia</b> (in-vitro hemolysis, polycythemia/leukocytosis), metabolic acidosis, insulin deficiency/hyperglycemia/hyperosmolality, increased catabolism (trauma, tumor lysis), β-blockade, exercise, digitalis overdose."},
 {"cat":"Hyperkalemia","q":"List causes of reduced urinary K⁺ excretion.",
  "a": "Renal failure; hypoaldosteronism (primary/secondary); volume depletion; <b>type IV RTA</b>; drugs impairing aldosterone secretion (<b>ACEIs, ARBs, NSAIDs, cyclosporin</b>); drugs causing aldosterone resistance (<b>spironolactone, trimethoprim, heparin</b>)."},
 {"cat":"Hyperkalemia","q":"What are the manifestations of hyperkalemia and the membrane mechanism?",
  "a": "High extracellular K⁺ <b>depolarizes the resting membrane potential</b> → nerve/muscle/cardiac cells become <b>less excitable</b> → muscle weakness/paralysis, paresthesias, impaired cardiac conduction, irregular pulse, cardiac standstill."},
 {"cat":"Hyperkalemia","q":"Describe the stepwise treatment of hyperkalemia.",
  "a": "Urgent if weakness/paralysis, ECG changes, arrhythmia, or K ≥7. <ul><li><b>1. Stabilize membrane:</b> IV calcium gluconate (10 ml over 10 min)</li><li><b>2. Shift K⁺ into cells:</b> β₂-agonists (salbutamol inhaled; avoid in IHD), insulin + dextrose, NaHCO₃ (rapid, brief)</li><li><b>3. Remove K⁺:</b> loop diuretics, K⁺ exchange resins (sodium polystyrene sulfonate — intestinal necrosis risk), <b>hemodialysis</b> (refractory/emergency, K &gt;7 or ECG changes)</li><li><b>4. Monitor:</b> continuous ECG + serial K at 1–2 h</li></ul>"},
 {"cat":"Hyperkalemia","q":"Give the ECG sequence of hyperkalemia.",
  "a": "Early: <b>tall peaked T waves</b> → intermediate: <b>PR prolongation, ST depression, loss of P waves</b> → late/severe: <b>widened QRS, VT, cardiac standstill</b> (sine wave). ECG changes = emergency trigger — treat immediately."},
 {"cat":"Hypokalemia","q":"Define hypokalemia and list its causes.",
  "a": "Serum K <b>&lt;3.5 mmol/L</b>. Causes: spurious (sample left at room temp, leukocytosis, recent insulin); ↓ intake; shift into cells (alkalosis, insulin, β-agonists, stress); <b>renal loss</b> (diuretics → RAAS activation, hyperaldosteronism/steroids, proximal RTA, hypomagnesemia, polyuria); extra-renal loss (vomiting/gastric aspiration → alkalosis + volume depletion → aldosterone)."},
 {"cat":"Hypokalemia","q":"Compare Bartter and Gitelman syndromes.",
  "a": "<b>Bartter:</b> impaired Na-Cl reabsorption in the <b>loop of Henle</b> — findings mimic a loop diuretic, <b>increased urinary calcium</b>, diagnosed in childhood, may have growth/mental retardation. <b>Gitelman:</b> defect in the <b>distal Na-Cl transporter</b> — findings mimic a thiazide diuretic."},
 {"cat":"Hypokalemia","q":"What causes hypokalemic periodic paralysis?",
  "a": "A defect in a <b>voltage-gated calcium channel</b>; triggered by strenuous exercise followed by rest, high-carbohydrate or high-sodium meals, and sudden temperature changes."},
 {"cat":"Hypokalemia","q":"Describe the ECG of hypokalemia.",
  "a": "<b>ST-segment and T-wave depression with prominent U waves</b>."},
 {"cat":"Hypokalemia","q":"How is hypokalemia treated?",
  "a": "Treat the cause. IV KCl when serum K <b>&lt;2.5 mmol/L</b>; max rate <b>&lt;20 mmol/hour</b>. Oral K preferred otherwise. <b>Check serum Mg</b> — potassium cannot be restored if magnesium is low. ECG monitoring required."},
]

# ============================================================
# GROUP 05 — Structural & Vascular Renal Diseases
# ============================================================
structural = [
 {"cat":"Cysts","q":"What is the incidence and nature of simple (solitary) renal cysts?",
  "a": "Common — in <b>50% of persons &gt;50 years</b>; not inherited; do not affect renal function; usually &lt;2 cm, solitary, cortical, often bulging through the renal capsule; may be multiple &amp; bilateral."},
 {"cat":"Cysts","q":"When are simple renal cysts symptomatic, and what complications can occur?",
  "a": "Rarely: abdominal mass; <b>hematuria (rare — raises suspicion of renal cell carcinoma)</b>; hypertension from compression of intra-renal vessels. Complications: hemorrhage, infection (fever, pain, pyuria), carcinoma. Renal function stays normal; prognosis excellent."},
 {"cat":"Cysts","q":"What are the ultrasound criteria of a simple renal cyst?",
  "a": "<ul><li>Echoes-free (homogeneous)</li><li>Sharply demarcated with a smooth thin wall</li><li><b>Enhanced back wall</b></li></ul>On CT: no enhancement with contrast — <b>a simple cyst does not enhance; renal cell carcinoma does</b>."},
 {"cat":"Cysts","q":"How are simple renal cysts differentiated from renal abscess and PCKD?",
  "a": "<b>Abscess:</b> fever, pain, pyuria; thick irregular wall with internal echoes/debris. <b>PCKD:</b> multiple bilateral cysts, family history, systemic involvement, renal failure, hypertension, extra-renal cysts."},
 {"cat":"Cysts","q":"How is a simple renal cyst managed?",
  "a": "Asymptomatic → periodic re-evaluation. Large cyst → aspiration + alcohol instillation; if &gt;500 ml of fluid → surgical drainage. Infected cyst → antibiotics (exclude abscess). Hypertension may improve after decompression."},
 {"cat":"ADPKD","q":"Give the genetics of ADPKD.",
  "a": "Autosomal dominant; defect on <b>chromosome 16 → ADPKD-1</b>, <b>chromosome 4 → ADPKD-2</b>. Common age of presentation: middle age (~40 y). It is a <b>systemic disease</b>."},
 {"cat":"ADPKD","q":"List the renal clinical features of ADPKD with their mechanisms.",
  "a": "Hematuria (cyst rupture into pelvis, stone, UTI); renal infection (flank pain, fever — urine may be normal because the cyst doesn't communicate with the urinary tract — <b>use blood cultures</b>); nephrolithiasis (mainly calcium oxalate); abdominal/flank pain (infection, bleeding, rupture, stones); <b>hypertension in ~50%</b> (cyst-induced ischemia → RAAS activation); mild anemia relative to renal failure; palpable irregular kidneys."},
 {"cat":"ADPKD","q":"List the extra-renal associations of ADPKD.",
  "a": "Hepatic cysts (50%, usually no functional impairment); pancreatic and splenic cysts; colonic diverticulosis; <b>cerebral berry aneurysms → subarachnoid hemorrhage</b>; mitral valve prolapse, aortic valve abnormalities, aortic aneurysms."},
 {"cat":"ADPKD","q":"How is ADPKD diagnosed?",
  "a": "Clinical: middle age, family history (<b>75%</b>), hematuria/mild proteinuria, slow steady decline in renal function. Imaging: US — <b>≥5 cysts scattered in cortex and medulla of each kidney</b>; CT if US unclear; IVP shows stretching/distortion of calyces."},
 {"cat":"ADPKD","q":"How is renal infection in ADPKD treated?",
  "a": "Parenteral antibiotics with cyst penetration (<b>ciprofloxacin, trimethoprim-sulfamethoxazole</b>) for 2 weeks followed by long-term oral therapy (months)."},
 {"cat":"ADPKD","q":"What are the key treatment cautions in ADPKD?",
  "a": "ACEIs/ARBs used with caution in renal impairment (especially with large cysts); diuretics cautiously (hypokalemia may promote cyst development); hematuria usually resolves in 7 days with bed rest + hydration — <b>recurrent bleeding suggests renal cell carcinoma</b>; renal failure: treat as usual but <b>avoid peritoneal dialysis</b>."},
 {"cat":"ARPKD","q":"Give the genetics and presentation of ARPKD.",
  "a": "Autosomal recessive, defect on <b>chromosome 6</b>; parents unaffected. Presents perinatally (<b>pulmonary hypoplasia → high mortality</b>), in early life (liver-dominant: hepatic fibrosis, portal hypertension, GI bleeding, hepatosplenomegaly), or later (renal-dominant: abdominal mass, HTN, recurrent UTIs, renal failure in adolescence). May associate with berry/aortic aneurysms and Ehlers-Danlos."},
 {"cat":"ARPKD","q":"How is ARPKD diagnosed?",
  "a": "US is the test of choice: <b>enlarged kidneys, smooth, increased echogenicity</b> (normal US does not exclude). Confirmed by absent family history (normal US in parents), liver cysts, and other ARPKD manifestations."},
 {"cat":"HTN-Nephrosclerosis","q":"Define hypertensive nephrosclerosis.",
  "a": "Chronic kidney disease that <b>complicates arterial hypertension</b> — a diagnosis based on <b>clinical criteria, not renal biopsy</b>."},
 {"cat":"HTN-Nephrosclerosis","q":"List the 5 clinical criteria for diagnosing hypertensive nephrosclerosis.",
  "a": "<ol><li>History of <b>prolonged hypertension (&gt;10 years)</b></li><li><b>Low-grade proteinuria (&lt;2 gm/day)</b></li><li>Grade I or II hypertensive retinopathy</li><li><b>Small scarred kidneys</b></li><li>No evidence of primary renal disease</li></ol>"},
 {"cat":"HTN-Nephrosclerosis","q":"What is the BP goal in CKD and which diuretic principle applies?",
  "a": "Intensive BP goal <b>&lt;130/80 mmHg</b>; low-salt diet is critical. <b>Diuretics are the cornerstone</b> — as GFR falls, higher diuretic doses are needed to achieve a natriuretic response."},
 {"cat":"HTN-Nephrosclerosis","q":"Which antihypertensives are used in proteinuric CKD, and which cautions apply?",
  "a": "<b>ACEIs/ARBs</b> first-line. <b>Non-dihydropyridine CCBs</b> (verapamil/diltiazem) reduce albuminuria and slow decline. <b>Dihydropyridine CCBs must NOT be monotherapy</b> in proteinuric CKD — always combine with a RAAS blocker. <b>Mineralocorticoid antagonists (spironolactone)</b> are fourth-line for resistant HTN but limited in advanced CKD by <b>hyperkalemia and AKI</b> risk."},
]

ALL_IM = [
    ("01_Glomerular_Diseases", "Glomerular Diseases", glomerular),
    ("02_Acute_Kidney_Injury", "Acute Kidney Injury & AKI in Special Situations", aki),
    ("03_Chronic_Kidney_Disease_and_RRT", "Chronic Kidney Disease & Renal Replacement Therapy", ckd),
    ("04_Electrolytes_and_Acid_Base", "Electrolytes & Acid-Base Disturbances", electrolytes),
    ("05_Structural_and_Vascular_Renal_Diseases", "Structural & Vascular Renal Diseases", structural),
]
